/* createstructure_emoji library
 * By Castellani Davide (@DavideC03)
 */

#ifndef CREATESTRUCTURE_EMOJI
// If not imported yet
#define CREATESTRUCTURE_EMOJI

// Dependencies
#include <bits/stdc++.h>

// using ...
using namespace std;

// Definitions
// #define DEBUG

// Declared functions
string emoji(string emojiCode);

// Function(s)
map <string, string> getEmoji();
string getEmoji(string emojiCode);

string getEmoji (string emojiCode) {
        /* Emoji: return an emoji by given code
         *
         * inputs:
         *      - emojiCode: the code of the emoji
         *
         * output:
         *      - the emoji
         */
	try {
		return getEmoji()[emojiCode];
	} catch (...) {
		return "emoji not found";
	}
}

map <string, string> getEmoji() {
        /* Emoji: return an emoji by given code
         *
         * output:
         *      - all the emoji(s)
         */
	map <string, string> emoji =
	{
		{"!!", "‼️"},
		{"!", "❗"},
		{"!?", "⁉️"},
		{"*", "❇️"},
		{"+", "➕"},
		{"+1", "👍🏿"},
		{"-", "➖"},
		{"-1", "👎🏿"},
		{"00", "🕚"},
		{"1", "🕜"},
		{"10", "🕥"},
		{"100", "💯"},
		{"10:00", "🕙"},
		{"10:30", "🕥"},
		{"11", "🕦"},
		{"11:00", "🕚"},
		{"11:30", "🕦"},
		{"12", "🕧"},
		{"1234", "🔢"},
		{"12:00", "🕛"},
		{"12:30", "🕧"},
		{"18", "🔞"},
		{"1:00", "🕐"},
		{"1:30", "🕜"},
		{"1st place medal", "🥇"},
		{"2", "🕝"},
		{"2:00", "🕑"},
		{"2:30", "🕝"},
		{"2nd place medal", "🥈"},
		{"3", "🕞"},
		{"3:00", "🕒"},
		{"3:30", "🕞"},
		{"3rd place medal", "🥉"},
		{"4", "🕟"},
		{"4:00", "🕓"},
		{"4:30", "🕟"},
		{"5", "🕠"},
		{"5:00", "🕔"},
		{"5:30", "🕠"},
		{"6", "🕡"},
		{"6:00", "🕕"},
		{"6:30", "🕡"},
		{"7", "🕢"},
		{"7:00", "🕖"},
		{"7:30", "🕢"},
		{"8", "🎱"},
		{"8:00", "🕗"},
		{"8:30", "🕣"},
		{"9", "🕤"},
		{"9:00", "🕘"},
		{"9:30", "🕤"},
		{"?", "❔"},
		{"A button (blood type)", "🅰️"},
		{"AB button (blood type)", "🆎"},
		{"ABCD", "🔠"},
		{"ATM sign", "🏧"},
		{"Africa", "🌍"},
		{"Americas", "🌎"},
		{"Aquarius", "♒"},
		{"Aries", "♈"},
		{"Asia", "🌏"},
		{"Australia", "🌏"},
		{"B button (blood type)", "🅱️"},
		{"BACK arrow", "🔙"},
		{"Buddhist", "☸️"},
		{"CL button", "🆑"},
		{"COOL button", "🆒"},
		{"Cancer", "♋"},
		{"Capricorn", "♑"},
		{"Christian", "☦️"},
		{"Christmas", "🎄"},
		{"Claus", "🧑🏿‍🎄"},
		{"David", "✡️"},
		{"Dracula", "🧛🏿‍♂️"},
		{"END arrow", "🔚"},
		{"Europe", "🌍"},
		{"European", "🏰"},
		{"FREE button", "🆓"},
		{"Gemini", "♊"},
		{"Hindu", "🕉️"},
		{"ID button", "🆔"},
		{"ILY", "🤟🏿"},
		{"Japan", "🗾"},
		{"Japanese acceptable button", "🉑"},
		{"Japanese application button", "🈸"},
		{"Japanese bargain button", "🉐"},
		{"Japanese congratulations button", "㊗️"},
		{"Japanese discount button", "🈹"},
		{"Japanese dolls", "🎎"},
		{"Japanese free of charge button", "🈚"},
		{"Japanese here button", "🈁"},
		{"Japanese monthly amount button", "🈷️"},
		{"Japanese no vacancy button", "🈵"},
		{"Japanese not free of charge button", "🈶"},
		{"Japanese open for business button", "🈺"},
		{"Japanese passing grade button", "🈴"},
		{"Japanese post office", "🏣"},
		{"Japanese prohibited button", "🈲"},
		{"Japanese reserved button", "🈯"},
		{"Japanese secret button", "㊙️"},
		{"Japanese service charge button", "🈂️"},
		{"Japanese symbol for beginner", "🔰"},
		{"Japanese vacancy button", "🈳"},
		{"Japanese", "🎌"},
		{"Jew", "✡️"},
		{"Jewish", "✡️"},
		{"Jolly Roger", "🏴‍☠️"},
		{"Leo", "♌"},
		{"Libra", "♎"},
		{"Mauritius", "🦤"},
		{"Mrs. Claus", "🤶🏿"},
		{"Mrs.", "🤶🏿"},
		{"Muslim", "☪️"},
		{"NEW button", "🆕"},
		{"NG button", "🆖"},
		{"O button (blood type)", "🅾️"},
		{"OK button", "🆗"},
		{"OK", "🆗"},
		{"ON! arrow", "🔛"},
		{"Oberon", "🧚🏿‍♂️"},
		{"Ophiuchus", "⛎"},
		{"P button", "🅿️"},
		{"Pisces", "♓"},
		{"Puck", "🧚🏿‍♂️"},
		{"SOON arrow", "🔜"},
		{"SOS button", "🆘"},
		{"Sagittarius", "♐"},
		{"Santa Claus", "🎅🏿"},
		{"Scorpio", "♏"},
		{"Statue of Liberty", "🗽"},
		{"Swiss", "🫕"},
		{"T-Rex", "🦖"},
		{"TOP arrow", "🔝"},
		{"Taurus", "♉"},
		{"Titania", "🧚🏿‍♀️"},
		{"Tokyo", "🗼"},
		{"Triton", "🧜🏿‍♂️"},
		{"Tyrannosaurus Rex", "🦖"},
		{"UFO", "🛸"},
		{"UP! button", "🆙"},
		{"VS button", "🆚"},
		{"Virgo", "♍"},
		{"WC", "🚻"},
		{"a", "🅰️"},
		{"ab", "🆎"},
		{"abacus", "🧮"},
		{"abc", "🔤"},
		{"abcd", "🔡"},
		{"absentminded", "😶‍🌫️"},
		{"absorbing", "🧽"},
		{"acceptable", "🉑"},
		{"access", "♿"},
		{"accessibility", "🛗"},
		{"accordian", "🪗"},
		{"accordion", "🪗"},
		{"accounting", "🧾"},
		{"actor", "👩🏿‍🎤"},
		{"adhesive bandage", "🩹"},
		{"admission tickets", "🎟️"},
		{"admission", "🎫"},
		{"adore", "🥰"},
		{"adult", "👵🏿"},
		{"aerial", "🚡"},
		{"aeroplane", "🛬"},
		{"aesculapius", "⚕️"},
		{"afro", "🦱"},
		{"age restriction", "🔞"},
		{"agreement", "🤝🏿"},
		{"aid", "⛑️"},
		{"airplane arrival", "🛬"},
		{"airplane", "🛬"},
		{"alarm", "⏰"},
		{"alembic", "⚗️"},
		{"alien", "👾"},
		{"alpaca", "🦙"},
		{"alphabet", "🔤"},
		{"ambulance", "🚑"},
		{"american", "🏈"},
		{"amoeba", "🦠"},
		{"amphora", "🏺"},
		{"amusement park", "🎢"},
		{"anatomical", "🫀"},
		{"anchor", "🔱"},
		{"angel", "👼🏿"},
		{"anger symbol", "💢"},
		{"anger", "😠"},
		{"angry face with horns", "👿"},
		{"angry", "🗯️"},
		{"anguished", "😧"},
		{"annelid", "🪱"},
		{"ant", "🐜"},
		{"antenna bars", "📶"},
		{"antenna", "📶"},
		{"anticlockwise", "🔄"},
		{"anxious face with sweat", "😰"},
		{"ape", "🦧"},
		{"apology", "🙇🏿‍♀️"},
		{"apple", "🍏"},
		{"application", "🈸"},
		{"archer", "♐"},
		{"architect", "👩🏿‍💼"},
		{"arctic", "🐻‍❄️"},
		{"arepa", "🫓"},
		{"army", "🪖"},
		{"arrivals", "🛬"},
		{"arriving", "🛬"},
		{"arrow", "⏬"},
		{"art", "🎨"},
		{"articulated lorry", "🚛"},
		{"artist palette", "🎨"},
		{"artist", "👩🏿‍🎨"},
		{"ashes", "⚱️"},
		{"ask", "🙏🏿"},
		{"assembly", "👩🏿‍🏭"},
		{"assistance", "🐕‍🦺"},
		{"asterisk", "✳️"},
		{"astonished", "😲"},
		{"astronaut", "👩🏿‍🚀"},
		{"atheist", "⚛️"},
		{"athletic", "👟"},
		{"athletics", "🎽"},
		{"atm", "🏧"},
		{"atom symbol", "⚛️"},
		{"atom", "⚛️"},
		{"attraction", "🧲"},
		{"aubergine", "🍆"},
		{"australia", "🪃"},
		{"auto rickshaw", "🛺"},
		{"automated", "🏧"},
		{"automobile", "🚘"},
		{"autumn", "🥮"},
		{"avocado", "🥑"},
		{"axe", "🪓"},
		{"b", "🅱️"},
		{"baby symbol", "🚼"},
		{"baby", "🚼"},
		{"back", "🔙"},
		{"backhand index pointing down", "👇🏿"},
		{"backhand index pointing left", "👈🏿"},
		{"backhand index pointing right", "👉🏿"},
		{"backhand index pointing up", "👆🏿"},
		{"backhand", "👇🏿"},
		{"backpack", "🎒"},
		{"backpacking", "🥾"},
		{"bacon", "🥓"},
		{"bacteria", "🧫"},
		{"bactrian", "🐫"},
		{"badge", "📛"},
		{"badger", "🦡"},
		{"badminton", "🏸"},
		{"bag", "💰"},
		{"bagel", "🥯"},
		{"baggage", "🛅"},
		{"baguette", "🥖"},
		{"bait", "🪤"},
		{"bakery", "🧁"},
		{"balance", "♎"},
		{"bald", "👩🏿‍🦲"},
		{"ball", "🧶"},
		{"ballet flat", "🥿"},
		{"ballet shoes", "🩰"},
		{"ballet", "🩰"},
		{"balloon", "🎈"},
		{"ballot box with ballot", "🗳️"},
		{"ballot", "🗳️"},
		{"ballpoint", "🖊️"},
		{"bamboo", "🎍"},
		{"banana", "🍌"},
		{"bandage", "🩹"},
		{"bangbang", "‼️"},
		{"banjo", "🪕"},
		{"bank", "💱"},
		{"banknote", "💸"},
		{"banner", "🎋"},
		{"bar", "📶"},
		{"barber", "💈"},
		{"bargain", "🉐"},
		{"barrier", "🚧"},
		{"baseball cap", "🧢"},
		{"baseball", "⚾"},
		{"basket", "🧺"},
		{"basketball", "🏀"},
		{"bat", "🏓"},
		{"bath", "🛁"},
		{"bathing suit", "🩳"},
		{"bathing", "🧼"},
		{"bathroom", "🪥"},
		{"bathtub", "🛁"},
		{"battery", "🔋"},
		{"beach sandals", "🩴"},
		{"beach with umbrella", "🏖️"},
		{"beach", "🏖️"},
		{"beacon", "🚨"},
		{"bead", "🧿"},
		{"beads", "📿"},
		{"beaming face with smiling eyes", "😁"},
		{"bear", "🐨"},
		{"beard", "🧔🏿‍♀️"},
		{"bearer", "⛎"},
		{"beat", "🪘"},
		{"beating heart", "💓"},
		{"beating", "💓"},
		{"beauty", "💇🏿"},
		{"beaver", "🦫"},
		{"bed", "🛏️"},
		{"bee", "🐝"},
		{"beer", "🍻"},
		{"beetle", "🐞"},
		{"begging", "🥺"},
		{"beginner", "🔰"},
		{"bell pepper", "🫑"},
		{"bell with slash", "🔕"},
		{"bell", "🔕"},
		{"bellhop", "🛎️"},
		{"bento", "🍱"},
		{"berries", "🍒"},
		{"berry", "🫐"},
		{"beverage", "🧃"},
		{"biceps", "💪🏿"},
		{"bicycle", "🚳"},
		{"bicyclist", "🚵🏿"},
		{"bike", "🚳"},
		{"biking", "🚵🏿‍♀️"},
		{"bikini", "👙"},
		{"bilberry", "🫐"},
		{"bill", "💸"},
		{"billed cap", "🧢"},
		{"billiard", "🎱"},
		{"biohazard", "☣️"},
		{"biologist", "🧬"},
		{"biology", "🧫"},
		{"bird", "🦜"},
		{"birdie", "🏸"},
		{"birthday", "🎂"},
		{"bison", "🦬"},
		{"bisque", "🦞"},
		{"black circle", "⚫"},
		{"black flag", "🏴"},
		{"black heart", "🖤"},
		{"black large square", "⬛"},
		{"black medium square", "◼️"},
		{"black medium-small square", "◾"},
		{"black nib", "✒️"},
		{"black small square", "▪️"},
		{"black square button", "🔲"},
		{"black", "🐈‍⬛"},
		{"bleed", "🩸"},
		{"blind", "🦯"},
		{"blond hair", "👱🏿‍♀️"},
		{"blond", "👱🏿‍♂️"},
		{"blond-haired man", "👱🏿‍♂️"},
		{"blond-haired person", "👱🏿"},
		{"blond-haired woman", "👱🏿‍♀️"},
		{"blonde", "👱🏿‍♀️"},
		{"blood donation", "🩸"},
		{"blood type", "🅾️"},
		{"blossom", "🌼"},
		{"blow", "🌬️"},
		{"blowfish", "🐡"},
		{"blu-ray", "📀"},
		{"blue heart", "💙"},
		{"blue", "🔹"},
		{"blue-faced", "🥶"},
		{"blueberries", "🫐"},
		{"blueberry", "🫐"},
		{"blush", "😊"},
		{"boar", "🐗"},
		{"board", "🛹"},
		{"boat", "🚢"},
		{"body", "👅"},
		{"bok choy", "🥬"},
		{"bolt", "🔩"},
		{"bomb", "💣"},
		{"bone", "🍗"},
		{"book", "📚"},
		{"bookkeeping", "🧾"},
		{"bookmark", "🔖"},
		{"books", "📚"},
		{"boom", "💥"},
		{"boomerang", "🪃"},
		{"boot", "👢"},
		{"bored", "🥱"},
		{"boring", "🪴"},
		{"bottle with popping cork", "🍾"},
		{"bottle", "🍾"},
		{"boulder", "🪨"},
		{"bouquet", "💐"},
		{"bow and arrow", "🏹"},
		{"bow", "🏹"},
		{"bowing", "🙇🏿‍♀️"},
		{"bowl with spoon", "🥣"},
		{"bowl", "🍜"},
		{"bowling", "🎳"},
		{"box", "☑️"},
		{"boxing", "🥊"},
		{"boy", "👩‍👧‍👦"},
		{"brachiosaurus", "🦕"},
		{"brain", "🧠"},
		{"bread", "🥪"},
		{"break", "💔"},
		{"breakfast", "🍩"},
		{"breast", "🤱🏿"},
		{"breast-feeding", "🤱🏿"},
		{"breath", "🫁"},
		{"brick", "🧱"},
		{"bricks", "🧱"},
		{"bride", "👰🏿"},
		{"bridge at night", "🌉"},
		{"bridge", "🌉"},
		{"briefcase", "💼"},
		{"briefs", "🩲"},
		{"bright button", "🔆"},
		{"bright", "🔆"},
		{"brightness", "🔆"},
		{"broccoli", "🥦"},
		{"broken heart", "💔"},
		{"broken", "💔"},
		{"brontosaurus", "🦕"},
		{"bronze", "🥉"},
		{"broom", "🧹"},
		{"brown", "🟫"},
		{"brush", "🪥"},
		{"bubble", "🧋"},
		{"bucket", "🪣"},
		{"buffalo", "🐃"},
		{"bug", "🪲"},
		{"building construction", "🏗️"},
		{"building", "🏭"},
		{"bulb", "💡"},
		{"bull", "♉"},
		{"bullet", "🚅"},
		{"bullseye", "🎯"},
		{"bunny ear", "👯‍♀️"},
		{"bunny", "🐇"},
		{"burger", "🍔"},
		{"burn", "❤️‍🔥"},
		{"burrito", "🌯"},
		{"bus", "🚏"},
		{"business", "🕴🏿"},
		{"busstop", "🚏"},
		{"bust in silhouette", "👤"},
		{"bust", "👥"},
		{"busts in silhouette", "👥"},
		{"butter", "🧈"},
		{"butterfly", "🦋"},
		{"button", "🔲"},
		{"c", "©️"},
		{"cabbage", "🥬"},
		{"cabinet", "🗄️"},
		{"cable", "🚡"},
		{"cactus", "🌵"},
		{"cake", "🍰"},
		{"calculation", "🧮"},
		{"calendar", "🗓️"},
		{"call me hand", "🤙🏿"},
		{"call", "🤙🏿"},
		{"camel", "🐫"},
		{"camera with flash", "📸"},
		{"camera", "🎦"},
		{"camping", "🥾"},
		{"can", "🥫"},
		{"cancel", "❌"},
		{"candelabrum", "🕎"},
		{"candle", "🕯️"},
		{"candlestick", "🕎"},
		{"candy", "🍭"},
		{"canned food", "🥫"},
		{"canoe", "🛶"},
		{"cap", "🎓"},
		{"capsicum", "🫑"},
		{"car", "🚡"},
		{"card", "🗃️"},
		{"cardinal", "⬅️"},
		{"cardiology", "🫀"},
		{"care", "💅🏿"},
		{"carousel", "🎠"},
		{"carp", "🎏"},
		{"carpenter", "🪚"},
		{"carpentry saw", "🪚"},
		{"carrot", "🥕"},
		{"cart", "🛒"},
		{"cartwheel", "🤸🏿‍♀️"},
		{"cask", "🪣"},
		{"casserole", "🥘"},
		{"castle", "🏰"},
		{"cat with tears of joy", "😹"},
		{"cat with wry smile", "😼"},
		{"cat", "🐈‍⬛"},
		{"catch", "🪝"},
		{"cd", "💿"},
		{"celebrate", "🥂"},
		{"celebration", "🎌"},
		{"cell", "📴"},
		{"cemetery", "🪦"},
		{"cereal", "🥣"},
		{"ceremony", "🎑"},
		{"chain", "⛓️"},
		{"chains", "⛓️"},
		{"chair", "🪑"},
		{"changing", "🚼"},
		{"chapel", "💒"},
		{"charm", "🧿"},
		{"chart decreasing", "📉"},
		{"chart increasing with yen", "💹"},
		{"chart increasing", "📈"},
		{"chart", "📊"},
		{"check box with check", "☑️"},
		{"check", "✔️"},
		{"check-in", "🛫"},
		{"checkered", "🏁"},
		{"cheering", "📣"},
		{"cheese wedge", "🧀"},
		{"cheese", "🫕"},
		{"chef", "👩🏿‍🍳"},
		{"chemist", "🧪"},
		{"chemistry", "🧪"},
		{"chemotherapy", "🦲"},
		{"chequered flag", "🏁"},
		{"chequered", "🏁"},
		{"cherries", "🍒"},
		{"cherry", "🍒"},
		{"chess pawn", "♟️"},
		{"chess", "♟️"},
		{"chest", "🧰"},
		{"chestnut", "🌰"},
		{"chevron", "🔰"},
		{"chick", "🐥"},
		{"chicken", "🍗"},
		{"chickpea", "🧆"},
		{"child", "🚸"},
		{"children crossing", "🚸"},
		{"chime", "🎐"},
		{"chipmunk", "🐿️"},
		{"chocolate", "🍫"},
		{"chop", "🪓"},
		{"chopsticks", "🥢"},
		{"christmas", "🧑🏿‍🎄"},
		{"church", "⛪"},
		{"cigarette", "🚬"},
		{"cinema", "🎦"},
		{"circle", "⚪"},
		{"circled M", "Ⓜ️"},
		{"circus", "🎪"},
		{"citrus", "🍋"},
		{"city", "🌆"},
		{"cityscape at dusk", "🌆"},
		{"cityscape", "🏙️"},
		{"cl", "🆑"},
		{"claim", "🛄"},
		{"clamp", "🗜️"},
		{"clap", "👏🏿"},
		{"clapper board", "🎬"},
		{"clapper", "🎬"},
		{"clapping hands", "👏🏿"},
		{"classical building", "🏛️"},
		{"classical", "🏛️"},
		{"claus", "🤶🏿"},
		{"claws", "🦞"},
		{"clay", "🧱"},
		{"clean", "🪥"},
		{"cleaning", "🧽"},
		{"clenched", "👊🏿"},
		{"climb", "🪜"},
		{"climber", "🧗🏿‍♀️"},
		{"clink", "🥂"},
		{"clinking beer mugs", "🍻"},
		{"clinking glasses", "🥂"},
		{"clipboard", "📋"},
		{"clock", "🕦"},
		{"clockwise vertical arrows", "🔃"},
		{"clockwise", "🔂"},
		{"closed mailbox with lowered flag", "📪"},
		{"closed mailbox with raised flag", "📫"},
		{"closed umbrella", "🌂"},
		{"closed", "🔐"},
		{"closet", "🚾"},
		{"clothing", "📿"},
		{"cloud with lightning and rain", "⛈️"},
		{"cloud with lightning", "🌩️"},
		{"cloud with rain", "🌧️"},
		{"cloud with snow", "🌨️"},
		{"cloud", "🌬️"},
		{"clover", "🍀"},
		{"clown", "🤡"},
		{"club suit", "♣️"},
		{"clue", "🗝️"},
		{"clutch bag", "👝"},
		{"coaster", "🎢"},
		{"coat", "🧥"},
		{"cockroach", "🪳"},
		{"cocktail", "🍸"},
		{"coconut", "🥥"},
		{"coder", "👩🏿‍💻"},
		{"coffee", "☕"},
		{"coffin", "⚰️"},
		{"cog", "⚙️"},
		{"cogwheel", "⚙️"},
		{"coin", "🪙"},
		{"cold face", "🥶"},
		{"cold", "💧"},
		{"collision", "💥"},
		{"comet", "☄️"},
		{"comic", "💠"},
		{"compass", "🧭"},
		{"compress", "🗜️"},
		{"computer mouse", "🖱️"},
		{"computer", "📀"},
		{"concertina", "🪗"},
		{"condiment", "🧂"},
		{"confetti", "🎊"},
		{"confounded", "😖"},
		{"confused", "😕"},
		{"conga", "🪘"},
		{"congee", "🥣"},
		{"congratulations", "㊗️"},
		{"construction", "🚧"},
		{"control", "🛂"},
		{"controller", "🎮"},
		{"convenience", "🏪"},
		{"cook", "👩🏿‍🍳"},
		{"cooked", "🍚"},
		{"cookie", "🍪"},
		{"cooking", "🏺"},
		{"cool", "🆒"},
		{"cop", "👮🏿‍♀️"},
		{"copyright", "©️"},
		{"cork", "🍾"},
		{"corn", "🌽"},
		{"cosmetics", "💄"},
		{"couch and lamp", "🛋️"},
		{"couch", "🛋️"},
		{"counterclockwise arrows button", "🔄"},
		{"counterclockwise", "🔄"},
		{"couple with heart", "👩🏿‍❤️‍👩🏿"},
		{"couple", "👩🏿‍❤️‍👩🏿"},
		{"cover", "📔"},
		{"cow", "🐄"},
		{"cowboy", "🤠"},
		{"cowgirl", "🤠"},
		{"crab", "♋"},
		{"cracker", "🍘"},
		{"crayon", "🖍️"},
		{"cream", "🍨"},
		{"creature", "👾"},
		{"credit", "💳"},
		{"crescent", "🌙"},
		{"cricket game", "🏏"},
		{"cricket", "🦗"},
		{"criminal", "🦹🏿‍♀️"},
		{"crochet", "🧶"},
		{"crocodile", "🐊"},
		{"croissant", "🥐"},
		{"crook", "🪝"},
		{"cross mark button", "❎"},
		{"cross", "🎌"},
		{"crossbones", "☠️"},
		{"crossed fingers", "🤞🏿"},
		{"crossed flags", "🎌"},
		{"crossed", "🎌"},
		{"crossing", "🚸"},
		{"crown", "👑"},
		{"crush", "🥰"},
		{"cry", "😿"},
		{"crying cat", "😿"},
		{"crying face", "😢"},
		{"crystal", "🔮"},
		{"crêpe", "🥞"},
		{"cucumber", "🥒"},
		{"culture", "🧫"},
		{"cup with straw", "🥤"},
		{"cup", "🍶"},
		{"cupcake", "🧁"},
		{"cupid", "💘"},
		{"curious", "🦝"},
		{"curl", "➿"},
		{"curling stone", "🥌"},
		{"curly hair", "👩🏿‍🦱"},
		{"curly loop", "➰"},
		{"curly", "🦱"},
		{"currency", "💲"},
		{"curry", "🍛"},
		{"curve", "🪝"},
		{"custard", "🍮"},
		{"customs", "🛃"},
		{"cut of meat", "🥩"},
		{"cutlery", "🍴"},
		{"cutting", "✂️"},
		{"cyclist", "🚵🏿‍♀️"},
		{"cyclone", "🌀"},
		{"cygnet", "🦢"},
		{"dagger", "🗡️"},
		{"dairy", "🧈"},
		{"dam", "🦫"},
		{"dance", "🩰"},
		{"dancer", "👯‍♀️"},
		{"dancing", "🕺🏿"},
		{"danger", "⚡"},
		{"dango", "🍡"},
		{"dark skin tone", "👩🏿‍❤️‍👩🏿"},
		{"dark", "🕶️"},
		{"dart", "🎯"},
		{"dash", "〰️"},
		{"dashing away", "💨"},
		{"date", "📅"},
		{"dazed", "😳"},
		{"dead", "😵"},
		{"deadpan", "😐"},
		{"deaf person", "🧏🏿"},
		{"deaf", "🧏🏿‍♀️"},
		{"death", "⚱️"},
		{"deciduous", "🌳"},
		{"decorated", "📔"},
		{"deer", "🦌"},
		{"dejected", "😔"},
		{"delicious", "😋"},
		{"delivery", "🚚"},
		{"demon", "👿"},
		{"demonstration", "🪧"},
		{"dental", "🪥"},
		{"dentist", "🦷"},
		{"department", "🏬"},
		{"departure", "🛫"},
		{"departures", "🛫"},
		{"derelict", "🏚️"},
		{"desert", "🏝️"},
		{"desktop", "🖥️"},
		{"dessert", "🍮"},
		{"detective", "🕵🏿‍♀️"},
		{"developer", "👩🏿‍💻"},
		{"devil", "👿"},
		{"dharma", "☸️"},
		{"dialog", "🗨️"},
		{"diamond suit", "♦️"},
		{"diamond with a dot", "💠"},
		{"diamond", "💠"},
		{"diaper", "🧷"},
		{"dice", "🎲"},
		{"die", "🎲"},
		{"diesel", "⛽"},
		{"dim button", "🔅"},
		{"dim", "🔅"},
		{"diplodocus", "🦕"},
		{"direct hit", "🎯"},
		{"direction", "↖️"},
		{"disappointed", "😞"},
		{"disbelief", "🤦🏿‍♀️"},
		{"discount", "🈹"},
		{"disease", "🪰"},
		{"disguise", "🥸"},
		{"disguised face", "🥸"},
		{"dish", "📡"},
		{"disk", "📀"},
		{"distrust", "🤨"},
		{"divide", "➗"},
		{"dividers", "🗂️"},
		{"diving mask", "🤿"},
		{"diving", "🤿"},
		{"division", "➗"},
		{"diya", "🪔"},
		{"dizzy", "🌀"},
		{"djinn", "🧞‍♀️"},
		{"dna", "🧬"},
		{"doctor", "🩺"},
		{"document", "📄"},
		{"dodo", "🦤"},
		{"dog", "🐩"},
		{"doll", "🪆"},
		{"dollar", "💲"},
		{"dolphin", "🐬"},
		{"donut", "🍩"},
		{"door", "🚪"},
		{"dotted six-pointed star", "🔯"},
		{"double curly loop", "➿"},
		{"double exclamation mark", "‼️"},
		{"double", "➿"},
		{"doubt", "🤷🏿‍♀️"},
		{"doughnut", "🍩"},
		{"dove", "🕊️"},
		{"down", "🔻"},
		{"down-left arrow", "↙️"},
		{"down-right arrow", "↘️"},
		{"downcast face with sweat", "😓"},
		{"downwards button", "🔽"},
		{"dragon", "🐉"},
		{"dress", "🥻"},
		{"drink", "🏺"},
		{"drinking", "🚰"},
		{"dromedary", "🐪"},
		{"drooling", "🤤"},
		{"drop of blood", "🩸"},
		{"drop", "💧"},
		{"droplet", "💧"},
		{"drum", "🪘"},
		{"drumstick", "🍗"},
		{"drumsticks", "🥁"},
		{"duck", "🦆"},
		{"dumpling", "🥟"},
		{"dung", "💩"},
		{"dupe", "♟️"},
		{"dusk", "🌇"},
		{"dvd", "📀"},
		{"dynamite", "🧨"},
		{"e-mail", "📩"},
		{"eagle", "🦅"},
		{"ear of corn", "🌽"},
		{"ear with hearing aid", "🦻🏿"},
		{"ear", "🌽"},
		{"earbud", "🎧"},
		{"earth", "🌐"},
		{"earthworm", "🪱"},
		{"east", "➡️"},
		{"egg", "🍳"},
		{"eggplant", "🍆"},
		{"eight", "🎱"},
		{"eight-pointed star", "✴️"},
		{"eight-spoked asterisk", "✳️"},
		{"eight-thirty", "🕣"},
		{"eighteen", "🔞"},
		{"eject button", "⏏️"},
		{"eject", "⏏️"},
		{"electric", "🔦"},
		{"electrician", "👩🏿‍🔧"},
		{"electricity", "🔌"},
		{"elephant", "🐘"},
		{"elevator", "🛗"},
		{"eleven", "🕦"},
		{"eleven-thirty", "🕦"},
		{"elf", "🧝🏿"},
		{"email", "📩"},
		{"emblem", "🔱"},
		{"embroidery", "🪡"},
		{"emergency", "🦺"},
		{"empanada", "🥟"},
		{"end", "🔚"},
		{"engine", "🚒"},
		{"engineer", "👩🏿‍🔬"},
		{"ensnare", "🪝"},
		{"entertainer", "👩🏿‍🎤"},
		{"entry", "🚫"},
		{"envelope with arrow", "📩"},
		{"envelope", "📩"},
		{"equestrian", "🐎"},
		{"eruption", "🌋"},
		{"euro", "💶"},
		{"evening", "🌆"},
		{"evergreen tree", "🌲"},
		{"evidence", "🧾"},
		{"evil", "🦹🏿‍♀️"},
		{"evil-eye", "🧿"},
		{"evolution", "🧬"},
		{"ewe", "🐑"},
		{"exasperation", "🤦🏿‍♀️"},
		{"exchange", "💱"},
		{"excited", "💗"},
		{"exclamation", "❗"},
		{"exhalation", "🫁"},
		{"exhale", "😮‍💨"},
		{"expendable", "♟️"},
		{"experiment", "🧪"},
		{"exploding head", "🤯"},
		{"explosive", "🧨"},
		{"expressionless", "😑"},
		{"extinction", "🦤"},
		{"extinguish", "🧯"},
		{"extraterrestrial", "👾"},
		{"eye in speech bubble", "👁️‍🗨️"},
		{"eye protection", "🥽"},
		{"eye", "🕶️"},
		{"eyeglasses", "👓"},
		{"eyeroll", "🙄"},
		{"eyes", "👀"},
		{"eyewear", "🕶️"},
		{"face blowing a kiss", "😘"},
		{"face exhaling", "😮‍💨"},
		{"face in clouds", "😶‍🌫️"},
		{"face in the fog", "😶‍🌫️"},
		{"face savoring food", "😋"},
		{"face screaming in fear", "😱"},
		{"face vomiting", "🤮"},
		{"face with hand over mouth", "🤭"},
		{"face with head-bandage", "🤕"},
		{"face with medical mask", "😷"},
		{"face with monocle", "🧐"},
		{"face with open mouth", "😮"},
		{"face with raised eyebrow", "🤨"},
		{"face with rolling eyes", "🙄"},
		{"face with spiral eyes", "😵‍💫"},
		{"face with steam from nose", "😤"},
		{"face with symbols on mouth", "🤬"},
		{"face with tears of joy", "😂"},
		{"face with thermometer", "🤒"},
		{"face with tongue", "😛"},
		{"face without mouth", "😶"},
		{"face", "🗿"},
		{"facepalm", "🤦🏿‍♀️"},
		{"factory", "🏭"},
		{"fairy tale", "🔮"},
		{"fairy", "🧚🏿"},
		{"falafel", "🧆"},
		{"fallen leaf", "🍂"},
		{"falling", "🌠"},
		{"family", "👩‍👧‍👧"},
		{"fantasy", "🔮"},
		{"farmer", "👩🏿‍🌾"},
		{"farming", "🧺"},
		{"fast down button", "⏬"},
		{"fast reverse button", "⏪"},
		{"fast up button", "⏫"},
		{"fast", "⏩"},
		{"fast-forward button", "⏩"},
		{"father", "🎅🏿"},
		{"favor", "🙇🏿‍♀️"},
		{"fax machine", "📠"},
		{"fax", "📠"},
		{"fear", "😱"},
		{"fearful", "😨"},
		{"feather", "🪶"},
		{"feeding", "🧑🏿‍🍼"},
		{"feet", "🐾"},
		{"female sign", "♀️"},
		{"female", "🐑"},
		{"fencer", "🤺"},
		{"fencing", "🤺"},
		{"ferris", "🎡"},
		{"ferry", "⛴️"},
		{"festival", "🎎"},
		{"fever", "🦟"},
		{"feverish", "🥵"},
		{"field", "🏑"},
		{"fighter", "🥷🏿"},
		{"file", "🗄️"},
		{"filing", "🗄️"},
		{"filling", "🥧"},
		{"film", "🎦"},
		{"finger", "☝🏿"},
		{"fingers", "🤌🏿"},
		{"fire extinguisher", "🧯"},
		{"fire", "🧯"},
		{"firecracker", "🧨"},
		{"firefighter", "👩🏿‍🚒"},
		{"firetruck", "👩🏿‍🚒"},
		{"fireworks", "🧨"},
		{"first quarter moon face", "🌛"},
		{"first quarter moon", "🌓"},
		{"first", "🥇"},
		{"fish cake with swirl", "🍥"},
		{"fish", "♓"},
		{"fishing pole", "🎣"},
		{"fishing", "🦦"},
		{"fist", "🤜🏿"},
		{"five", "🕠"},
		{"five-thirty", "🕠"},
		{"flag in hole", "⛳"},
		{"flag", "🏴󠁧󠁢󠁳󠁣󠁴󠁿"},
		{"flamboyant", "🦩"},
		{"flame", "🔥"},
		{"flamingo", "🦩"},
		{"flash", "📸"},
		{"flashlight", "🔦"},
		{"flat shoe", "🥿"},
		{"flatbread", "🥙"},
		{"flavoring", "🧅"},
		{"fleur-de-lis", "⚜️"},
		{"flex", "💪🏿"},
		{"flexed biceps", "💪🏿"},
		{"flight", "🪶"},
		{"flipper", "🐬"},
		{"floor", "🤣"},
		{"floppy", "💾"},
		{"flower playing cards", "🎴"},
		{"flower", "🎴"},
		{"fluctuate", "🪀"},
		{"flushed", "😳"},
		{"flutter", "🍃"},
		{"fly", "💸"},
		{"flying disc", "🥏"},
		{"flying saucer", "🛸"},
		{"fog", "🌫️"},
		{"foggy", "🌁"},
		{"folded hands", "🙏🏿"},
		{"folder", "📂"},
		{"fondue", "🫕"},
		{"food", "🦑"},
		{"foot", "🦶🏿"},
		{"football", "🏉"},
		{"footprint", "👣"},
		{"footprints", "👣"},
		{"forbidden", "📵"},
		{"force cup", "🪠"},
		{"forever", "♾️"},
		{"fork and knife with plate", "🍽️"},
		{"fork and knife", "🍴"},
		{"fork", "🍴"},
		{"fortune cookie", "🥠"},
		{"fortune", "🔯"},
		{"forward", "⏩"},
		{"fountain", "🖋️"},
		{"four", "🕟"},
		{"four-leaf clover", "🍀"},
		{"four-thirty", "🕟"},
		{"fox", "🦊"},
		{"frame", "🪟"},
		{"framed picture", "🖼️"},
		{"frames", "🎞️"},
		{"frankfurter", "🌭"},
		{"free of charge", "🈚"},
		{"free", "🆓"},
		{"freezing", "🥶"},
		{"french", "🍟"},
		{"fresh air", "🪟"},
		{"fried", "🍤"},
		{"fries", "🍟"},
		{"frog", "🐸"},
		{"front-facing baby chick", "🐥"},
		{"frostbite", "🥶"},
		{"frown", "🙍🏿"},
		{"frowning face with open mouth", "😦"},
		{"frowning face", "☹️"},
		{"frowning", "🙍🏿‍♀️"},
		{"fruit", "🥑"},
		{"frying", "🍳"},
		{"fuel", "⛽"},
		{"fuelpump", "⛽"},
		{"fuji", "🗻"},
		{"full", "🌝"},
		{"funeral", "⚱️"},
		{"game", "🎴"},
		{"garden", "🏡"},
		{"gardener", "👩🏿‍🌾"},
		{"garlic", "🧄"},
		{"gas", "⛽"},
		{"gasp", "😮‍💨"},
		{"gear", "⚙️"},
		{"geek", "🤓"},
		{"gem stone", "💎"},
		{"gem", "💎"},
		{"gender-neutral", "🧓🏿"},
		{"gene", "🧬"},
		{"genetics", "🧬"},
		{"genie", "🧞"},
		{"geometric", "🔲"},
		{"gesture", "🙇🏿‍♀️"},
		{"gesundheit", "🤧"},
		{"ghost", "👻"},
		{"gibbous", "🌖"},
		{"gift", "🎁"},
		{"ginger", "🦰"},
		{"giraffe", "🦒"},
		{"girl", "👩‍👧‍👧"},
		{"glass of milk", "🥛"},
		{"glass", "🔎"},
		{"glasses", "🕶️"},
		{"glittery", "🌟"},
		{"globe showing Americas", "🌎"},
		{"globe showing Asia-Australia", "🌏"},
		{"globe showing Europe-Africa", "🌍"},
		{"globe with meridians", "🌐"},
		{"globe", "🌐"},
		{"glove", "🥊"},
		{"gloves", "🧤"},
		{"glow", "🌟"},
		{"glowing star", "🌟"},
		{"goal", "🥅"},
		{"goat", "♑"},
		{"goblin", "👺"},
		{"goggles", "🥽"},
		{"gold", "🪙"},
		{"golf", "⛳"},
		{"gondola", "🚡"},
		{"good luck", "🧧"},
		{"good", "🦸🏿‍♀️"},
		{"goodbye", "🫂"},
		{"goofy", "🤪"},
		{"gorilla", "🦍"},
		{"graduate", "👩🏿‍🎓"},
		{"graduation", "🎓"},
		{"grain", "🌾"},
		{"grape", "🍇"},
		{"grapes", "🍇"},
		{"graph", "📊"},
		{"grasshopper", "🦗"},
		{"grateful", "🥲"},
		{"grave", "🪦"},
		{"graveyard", "🪦"},
		{"gray", "🦳"},
		{"green heart", "💚"},
		{"green", "🟩"},
		{"grimace", "😬"},
		{"grimacing face", "😬"},
		{"grin", "😸"},
		{"grinning cat with smiling eyes", "😸"},
		{"grinning face with big eyes", "😃"},
		{"grinning face with smiling eyes", "😄"},
		{"grinning face with sweat", "😅"},
		{"grinning face", "😀"},
		{"grinning squinting face", "😆"},
		{"grinning", "😺"},
		{"groan", "😮‍💨"},
		{"groom", "🤵🏿"},
		{"grow", "🪴"},
		{"growing heart", "💗"},
		{"growing", "💗"},
		{"growth", "📈"},
		{"gua pi mao", "👲🏿"},
		{"guanaco", "🦙"},
		{"guard", "💂🏿‍♀️"},
		{"guide dog", "🦮"},
		{"guide", "🦮"},
		{"guitar", "🎸"},
		{"gun", "🔫"},
		{"gymnastics", "🤸🏿‍♀️"},
		{"gyro", "🥙"},
		{"gyōza", "🥟"},
		{"hair", "👱🏿‍♀️"},
		{"haircut", "💈"},
		{"hairless", "🦲"},
		{"halloween", "🎃"},
		{"halo", "😇"},
		{"hamburger", "🍔"},
		{"hammer and pick", "⚒️"},
		{"hammer and wrench", "🛠️"},
		{"hammer", "🛠️"},
		{"hamster", "🐹"},
		{"hand gesture", "🤌🏿"},
		{"hand with fingers splayed", "🖐🏿"},
		{"hand", "🧤"},
		{"handbag", "👜"},
		{"handball", "🤾🏿‍♀️"},
		{"handgun", "🔫"},
		{"handshake", "🤝🏿"},
		{"hang-glide", "🪂"},
		{"happy", "🙋🏿"},
		{"hard of hearing", "🦻🏿"},
		{"hashi", "🥢"},
		{"hat", "⛑️"},
		{"hatchet", "🪓"},
		{"hatching", "🐣"},
		{"head in clouds", "😶‍🌫️"},
		{"head", "🗣️"},
		{"headphone", "🎧"},
		{"headscarf", "🧕🏿"},
		{"headstone", "🪦"},
		{"health worker", "🧑🏿‍⚕️"},
		{"healthcare", "👩🏿‍⚕️"},
		{"healthier", "❤️‍🩹"},
		{"hear", "🧏🏿"},
		{"hear-no-evil monkey", "🙉"},
		{"heart decoration", "💟"},
		{"heart exclamation", "❣️"},
		{"heart on fire", "❤️‍🔥"},
		{"heart suit", "♥️"},
		{"heart with arrow", "💘"},
		{"heart with ribbon", "💝"},
		{"heart", "🩺"},
		{"heartbeat", "💓"},
		{"hearts", "🥰"},
		{"heat stroke", "🥵"},
		{"heavy dollar sign", "💲"},
		{"heavy", "🪨"},
		{"hedgehog", "🦔"},
		{"heel", "👠"},
		{"helicopter", "🚁"},
		{"hello", "🫂"},
		{"helmet", "⛑️"},
		{"help", "🆘"},
		{"herb", "🌿"},
		{"herd", "🦬"},
		{"here", "🈁"},
		{"hero", "🦸🏿‍♀️"},
		{"heroine", "🦸🏿‍♀️"},
		{"hibiscus", "🌺"},
		{"hidden", "🥷🏿"},
		{"high 5", "🙏🏿"},
		{"high five", "🙏🏿"},
		{"high voltage", "⚡"},
		{"high-heeled shoe", "👠"},
		{"high-speed train", "🚄"},
		{"highway", "🛣️"},
		{"hijab", "🧕🏿"},
		{"hike", "🚶🏿‍♀️"},
		{"hiking", "🥾"},
		{"hindu", "🛕"},
		{"hippo", "🦛"},
		{"hippopotamus", "🦛"},
		{"hit", "🎯"},
		{"hocho", "🔪"},
		{"hockey", "🏒"},
		{"hoist", "🛗"},
		{"hold", "👫🏿"},
		{"holding hands", "👬🏿"},
		{"hole", "⛳"},
		{"hollow red circle", "⭕"},
		{"home", "🏡"},
		{"honey badger", "🦡"},
		{"honey", "🍯"},
		{"honeybee", "🐝"},
		{"honeypot", "🍯"},
		{"hook", "🪝"},
		{"hoop", "🏀"},
		{"hooray", "🙌🏿"},
		{"horizontal traffic light", "🚥"},
		{"horn", "📯"},
		{"horns", "🤘🏿"},
		{"horrible", "😝"},
		{"horse", "🎠"},
		{"horseshoe", "🧲"},
		{"hospital", "🏥"},
		{"hot dog", "🌭"},
		{"hot face", "🥵"},
		{"hot", "♨️"},
		{"hotcake", "🥞"},
		{"hotdog", "🌭"},
		{"hotel", "🛋️"},
		{"hotsprings", "♨️"},
		{"hourglass done", "⌛"},
		{"hourglass not done", "⏳"},
		{"hourglass", "⏳"},
		{"house with garden", "🏡"},
		{"house", "🏡"},
		{"houses", "🏘️"},
		{"hug", "🫂"},
		{"hugging", "🤗"},
		{"hump", "🐫"},
		{"hundred points", "💯"},
		{"hundred", "💯"},
		{"hurricane", "🌀"},
		{"hurt", "🤕"},
		{"hushed", "😯"},
		{"hut", "🛖"},
		{"hygiene", "🪥"},
		{"hypnotized", "😵‍💫"},
		{"hóngbāo", "🧧"},
		{"i", "ℹ️"},
		{"ice cube", "🧊"},
		{"ice", "⛸️"},
		{"iceberg", "🧊"},
		{"icecream", "🍦"},
		{"icicles", "🥶"},
		{"id", "🆔"},
		{"idea", "💡"},
		{"identity", "🆔"},
		{"ideograph", "🈵"},
		{"ignorance", "🤷🏿‍♀️"},
		{"ill", "🤒"},
		{"imp", "👿"},
		{"improving", "❤️‍🩹"},
		{"in love", "🥰"},
		{"inbox", "📥"},
		{"incognito", "🥸"},
		{"incoming", "📨"},
		{"indecisive", "🧇"},
		{"index pointing up", "☝🏿"},
		{"index", "📇"},
		{"indifference", "🤷🏿‍♀️"},
		{"industrial", "👩🏿‍🏭"},
		{"inexpressive", "😑"},
		{"infinity", "♾️"},
		{"information", "ℹ️"},
		{"inhalation", "🫁"},
		{"injury", "🩸"},
		{"ink", "🔏"},
		{"innocent", "😇"},
		{"input symbols", "🔣"},
		{"input", "🔤"},
		{"insect", "🕷️"},
		{"inside", "💠"},
		{"instructor", "👩🏿‍🏫"},
		{"instrument", "🎻"},
		{"intelligent", "🧠"},
		{"intercardinal", "↖️"},
		{"interlocking", "🧩"},
		{"interrobang", "⁉️"},
		{"interrogation", "🤌🏿"},
		{"intoxicated", "🥴"},
		{"inventor", "👩🏿‍💻"},
		{"iron", "🧇"},
		{"ironic", "😼"},
		{"islam", "☪️"},
		{"island", "🏝️"},
		{"jack", "🎃"},
		{"jack-o-lantern", "🎃"},
		{"jacket", "🧥"},
		{"jeans", "👖"},
		{"jewel", "💎"},
		{"jiaozi", "🥟"},
		{"jigsaw", "🧩"},
		{"jockey", "🏇🏿"},
		{"joey", "🦘"},
		{"joke", "😜"},
		{"joker", "🃏"},
		{"joy", "😹"},
		{"joystick", "🕹️"},
		{"judge", "👩🏿‍⚖️"},
		{"judo", "🥋"},
		{"jug", "🏺"},
		{"juggle", "🤹🏿"},
		{"juggling", "🤹🏿‍♀️"},
		{"juice", "🧃"},
		{"jump", "🦘"},
		{"justice", "♎"},
		{"kaaba", "🕋"},
		{"kale", "🥬"},
		{"kangaroo", "🦘"},
		{"karaoke", "🎤"},
		{"karate", "🥋"},
		{"katakana", "🈂️"},
		{"kebab", "🍢"},
		{"key", "🗝️"},
		{"keyboard", "⌨️"},
		{"keycap", "🔟"},
		{"kick", "🛴"},
		{"kimono", "👘"},
		{"king", "👑"},
		{"kiss mark", "💋"},
		{"kiss", "👩🏿‍❤️‍💋‍👩🏿"},
		{"kissing cat", "😽"},
		{"kissing face with closed eyes", "😚"},
		{"kissing face with smiling eyes", "😙"},
		{"kissing face", "😗"},
		{"kitchen knife", "🔪"},
		{"kite", "🪁"},
		{"kiwi", "🥝"},
		{"kneel", "🧎🏿"},
		{"kneeling", "🧎🏿‍♀️"},
		{"knife", "🗡️"},
		{"knit", "🧶"},
		{"knobs", "🎛️"},
		{"knocked out", "😵"},
		{"knocked-out face", "😵"},
		{"knot", "🪢"},
		{"koala", "🐨"},
		{"lab coat", "🥼"},
		{"lab", "🧫"},
		{"label", "🏷️"},
		{"lacrosse", "🥍"},
		{"ladder", "🪜"},
		{"lady beetle", "🐞"},
		{"ladybird", "🐞"},
		{"ladybug", "🐞"},
		{"lai see", "🧧"},
		{"lambchop", "🥩"},
		{"lamp", "🛋️"},
		{"landing", "🛬"},
		{"landscape", "🌆"},
		{"lantern", "🏮"},
		{"laptop", "💻"},
		{"large blue diamond", "🔷"},
		{"large orange diamond", "🔶"},
		{"large", "⭕"},
		{"last quarter moon face", "🌜"},
		{"last quarter moon", "🌗"},
		{"last track button", "⏮️"},
		{"lather", "🧼"},
		{"latin cross", "✝️"},
		{"latin", "🔤"},
		{"laugh", "😂"},
		{"laundry", "🧺"},
		{"lavash", "🫓"},
		{"lavatory", "🚾"},
		{"lazy", "🦥"},
		{"leaf fluttering in wind", "🍃"},
		{"leaf", "🔰"},
		{"leafy green", "🥬"},
		{"ledger", "📒"},
		{"left arrow curving right", "↪️"},
		{"left arrow", "⬅️"},
		{"left luggage", "🛅"},
		{"left speech bubble", "🗨️"},
		{"left", "◀️"},
		{"left-facing fist", "🤛🏿"},
		{"left-right arrow", "↔️"},
		{"leftwards", "🤛🏿"},
		{"leg", "🍗"},
		{"lemon", "🍋"},
		{"leopard", "🐆"},
		{"letter", "📥"},
		{"letters", "🔤"},
		{"lettuce", "🥬"},
		{"level", "🎚️"},
		{"liberty", "🗽"},
		{"lie", "🤥"},
		{"life", "🧬"},
		{"lift", "🛗"},
		{"lifter", "🏋🏿"},
		{"light blue", "🏳️‍⚧️"},
		{"light rail", "🚈"},
		{"light skin tone", "👩🏿‍❤️‍👩🏻"},
		{"light", "🏮"},
		{"lightning", "⚡"},
		{"limb", "🦵🏿"},
		{"link", "🔗"},
		{"linked paperclips", "🖇️"},
		{"lion", "♌"},
		{"lips", "👄"},
		{"lipstick", "💄"},
		{"liquor", "🥃"},
		{"litter bin", "🚮"},
		{"litter in bin sign", "🚮"},
		{"litter", "🚯"},
		{"lizard", "🦎"},
		{"llama", "🦙"},
		{"loaf", "🍞"},
		{"lobster", "🦞"},
		{"lock", "🗝️"},
		{"locked with key", "🔐"},
		{"locked with pen", "🔏"},
		{"locked", "🔒"},
		{"locker", "🛅"},
		{"locomotive", "🚂"},
		{"log", "🪵"},
		{"lollipop", "🍭"},
		{"long drum", "🪘"},
		{"loop", "➿"},
		{"lorry", "🚛"},
		{"lotion bottle", "🧴"},
		{"lotion", "🧴"},
		{"loud", "📢"},
		{"loudly crying face", "😭"},
		{"loudspeaker", "📢"},
		{"love", "🏩"},
		{"love-you gesture", "🤟🏿"},
		{"low", "🔅"},
		{"lowercase", "🔡"},
		{"lowered", "📭"},
		{"luck", "🤞🏿"},
		{"luggage", "🛅"},
		{"lumber", "🪚"},
		{"lungs", "🫁"},
		{"lust", "❤️‍🔥"},
		{"lying face", "🤥"},
		{"m", "Ⓜ️"},
		{"mad", "🗯️"},
		{"mage", "🧙🏿"},
		{"maggot", "🪰"},
		{"magic wand", "🪄"},
		{"magic", "🪄"},
		{"magical", "🧝🏿‍♀️"},
		{"magnet", "🧲"},
		{"magnetic", "🧲"},
		{"magnifying glass tilted left", "🔍"},
		{"magnifying glass tilted right", "🔎"},
		{"magnifying", "🔎"},
		{"mahjong red dragon", "🀄"},
		{"mahjong", "🀄"},
		{"mail", "📮"},
		{"mailbox", "📮"},
		{"maize", "🌽"},
		{"makeup", "💄"},
		{"malaria", "🦟"},
		{"male sign", "♂️"},
		{"male", "🐏"},
		{"mammoth", "🦣"},
		{"man bouncing ball", "⛹🏿‍♂️"},
		{"man cartwheeling", "🤸🏿‍♂️"},
		{"man climbing", "🧗🏿‍♂️"},
		{"man elf", "🧝🏿‍♂️"},
		{"man facepalming", "🤦🏿‍♂️"},
		{"man fairy", "🧚🏿‍♂️"},
		{"man genie", "🧞‍♂️"},
		{"man gesturing NO", "🙅🏿‍♂️"},
		{"man gesturing OK", "🙆🏿‍♂️"},
		{"man getting haircut", "💇🏿‍♂️"},
		{"man getting massage", "💆🏿‍♂️"},
		{"man golfing", "🏌🏿‍♂️"},
		{"man health worker", "👨🏿‍⚕️"},
		{"man in lotus position", "🧘🏿‍♂️"},
		{"man in manual wheelchair", "👨🏿‍🦽"},
		{"man in motorized wheelchair", "👨🏿‍🦼"},
		{"man in steamy room", "🧖🏿‍♂️"},
		{"man in tuxedo", "🤵🏿‍♂️"},
		{"man lifting weights", "🏋🏿‍♂️"},
		{"man mage", "🧙🏿‍♂️"},
		{"man mountain biking", "🚵🏿‍♂️"},
		{"man office worker", "👨🏿‍💼"},
		{"man playing handball", "🤾🏿‍♂️"},
		{"man playing water polo", "🤽🏿‍♂️"},
		{"man raising hand", "🙋🏿‍♂️"},
		{"man rowing boat", "🚣🏿‍♂️"},
		{"man shrugging", "🤷🏿‍♂️"},
		{"man superhero", "🦸🏿‍♂️"},
		{"man supervillain", "🦹🏿‍♂️"},
		{"man swimming", "🏊🏿‍♂️"},
		{"man tipping hand", "💁🏿‍♂️"},
		{"man vampire", "🧛🏿‍♂️"},
		{"man walking", "🚶🏿‍♂️"},
		{"man wearing turban", "👳🏿‍♂️"},
		{"man with veil", "👰🏿‍♂️"},
		{"man with white cane", "👨🏿‍🦯"},
		{"man zombie", "🧟‍♂️"},
		{"man", "♂️"},
		{"man: beard", "🧔🏿‍♂️"},
		{"man: blond hair", "👱🏿‍♂️"},
		{"manager", "👩🏿‍💼"},
		{"mango", "🥭"},
		{"manicure", "💅🏿"},
		{"mantelpiece clock", "🕰️"},
		{"mantilla", "🧕🏿"},
		{"manual wheelchair", "🦽"},
		{"man’s shoe", "👞"},
		{"map of Japan", "🗾"},
		{"map", "🗾"},
		{"maple", "🍁"},
		{"marathon", "🏃🏿‍♀️"},
		{"mark", "🆙"},
		{"marker", "📑"},
		{"marsupial", "🦘"},
		{"martial arts uniform", "🥋"},
		{"martial arts", "🥋"},
		{"mask", "🎭"},
		{"massage", "💆🏿‍♀️"},
		{"mate", "🧉"},
		{"math", "➗"},
		{"maze", "🌽"},
		{"meat on bone", "🍖"},
		{"meat", "🥓"},
		{"meatball", "🧆"},
		{"mechanic", "🧰"},
		{"mechanical arm", "🦾"},
		{"mechanical leg", "🦿"},
		{"medal", "🥉"},
		{"medical symbol", "⚕️"},
		{"medicine", "⚕️"},
		{"meditation", "🧘🏿‍♀️"},
		{"medium skin tone", "👩🏿‍❤️‍👩🏽"},
		{"medium", "🔉"},
		{"medium-dark skin tone", "👩🏿‍❤️‍👩🏾"},
		{"medium-dark skin", "🤝🏾"},
		{"medium-light skin tone", "👩🏿‍❤️‍👩🏼"},
		{"meeting", "🤝🏿"},
		{"megaphone", "📣"},
		{"meh", "😕"},
		{"melon", "🍈"},
		{"melted", "🫕"},
		{"memo", "📝"},
		{"men holding hands", "👬🏿"},
		{"men with bunny ears", "👯‍♂️"},
		{"men wrestling", "🤼‍♂️"},
		{"men", "👬🏿"},
		{"mending heart", "❤️‍🩹"},
		{"mending", "❤️‍🩹"},
		{"menorah", "🕎"},
		{"menstruation", "🩸"},
		{"men’s room", "🚹"},
		{"mercy", "🥺"},
		{"meridians", "🌐"},
		{"mermaid", "🧜🏿‍♀️"},
		{"merman", "🧜🏿‍♂️"},
		{"merperson", "🧜🏿"},
		{"merwoman", "🧜🏿‍♀️"},
		{"metal", "🪙"},
		{"metro", "🚇"},
		{"mexican", "🫔"},
		{"mic", "🎤"},
		{"microbe", "🦠"},
		{"microphone", "🎤"},
		{"microscope", "🔬"},
		{"middle finger", "🖕🏿"},
		{"military", "🪖"},
		{"milk", "🧋"},
		{"milky way", "🌌"},
		{"mind blown", "🤯"},
		{"minibus", "🚐"},
		{"minidisk", "💽"},
		{"mining", "⛏️"},
		{"minus", "➖"},
		{"mirror", "🪞"},
		{"moai", "🗿"},
		{"mobile phone with arrow", "📲"},
		{"mobile", "📴"},
		{"mode", "📳"},
		{"moisturizer", "🧴"},
		{"molusc", "🦑"},
		{"money with wings", "💸"},
		{"money", "💲"},
		{"money-mouth face", "🤑"},
		{"moneybag", "💰"},
		{"monkey", "🐒"},
		{"monorail", "🚝"},
		{"monster", "🤖"},
		{"monthly amount", "🈷️"},
		{"moon cake", "🥮"},
		{"moon viewing ceremony", "🎑"},
		{"moon", "🎑"},
		{"morning", "🌅"},
		{"mortar", "🧱"},
		{"mosque", "🕌"},
		{"mosquito", "🦟"},
		{"mother", "🤶🏿"},
		{"motor boat", "🛥️"},
		{"motor", "🛵"},
		{"motorboat", "🛥️"},
		{"motorcycle", "🏍️"},
		{"motorized wheelchair", "🦼"},
		{"motorway", "🛣️"},
		{"mount fuji", "🗻"},
		{"mountain cableway", "🚠"},
		{"mountain", "🚠"},
		{"mouse trap", "🪤"},
		{"mouse", "🐁"},
		{"mousetrap", "🪤"},
		{"mouth", "👄"},
		{"movie", "🎦"},
		{"moyai", "🗿"},
		{"mug", "🍻"},
		{"multiplication", "❌"},
		{"multiply", "❌"},
		{"multitask", "🤹🏿‍♀️"},
		{"munch", "😱"},
		{"muscle", "💪🏿"},
		{"museum", "🎨"},
		{"mushroom", "🍄"},
		{"music", "🥁"},
		{"musical keyboard", "🎹"},
		{"musical note", "🎵"},
		{"musical notes", "🎶"},
		{"musical score", "🎼"},
		{"mute", "🔕"},
		{"muted speaker", "🔇"},
		{"mx claus", "🧑🏿‍🎄"},
		{"naan", "🫓"},
		{"nail", "💅🏿"},
		{"name", "📛"},
		{"national park", "🏞️"},
		{"nauseated", "🤢"},
		{"navigation", "🧭"},
		{"nazar amulet", "🧿"},
		{"nazar", "🧿"},
		{"neck", "🧣"},
		{"necklace", "📿"},
		{"necktie", "👔"},
		{"needle", "💉"},
		{"nerd", "🤓"},
		{"nervous", "💗"},
		{"nesting dolls", "🪆"},
		{"nesting", "🪆"},
		{"net", "🥅"},
		{"neutral", "😐"},
		{"new moon face", "🌚"},
		{"new moon", "🌑"},
		{"new", "🆕"},
		{"news", "🗞️"},
		{"newspaper", "🗞️"},
		{"next scene", "⏭️"},
		{"next track button", "⏭️"},
		{"next track", "⏭️"},
		{"ng", "🆖"},
		{"nib", "🔏"},
		{"night with stars", "🌃"},
		{"night", "🌉"},
		{"nine", "🕤"},
		{"nine-thirty", "🕤"},
		{"ninja", "🥷🏿"},
		{"no bicycles", "🚳"},
		{"no hair", "🦲"},
		{"no littering", "🚯"},
		{"no mobile phones", "📵"},
		{"no one under eighteen", "🔞"},
		{"no pedestrians", "🚷"},
		{"no vacancy", "🈵"},
		{"no", "📵"},
		{"non-drinking", "🚱"},
		{"non-potable", "🚱"},
		{"noodle", "🍜"},
		{"north", "⬆️"},
		{"northeast", "↗️"},
		{"northwest", "↖️"},
		{"nose", "🐽"},
		{"not free of charge", "🈶"},
		{"not", "🚷"},
		{"note", "🗒️"},
		{"notebook with decorative cover", "📔"},
		{"notebook", "📒"},
		{"notes", "🎶"},
		{"numbers", "🔢"},
		{"nurse", "👩🏿‍⚕️"},
		{"nursing", "🧑🏿‍🍼"},
		{"nurturing", "🪴"},
		{"nut and bolt", "🔩"},
		{"nut", "🔩"},
		{"o", "🅾️"},
		{"ocean", "🌊"},
		{"octagonal", "🛑"},
		{"octopus", "🐙"},
		{"oden", "🍢"},
		{"off", "📴"},
		{"office building", "🏢"},
		{"office worker", "🧑🏿‍💼"},
		{"officer", "👮🏿‍♀️"},
		{"ogre", "👹"},
		{"oh", "🙀"},
		{"oil", "🪔"},
		{"old", "🗝️"},
		{"older person", "🧓🏿"},
		{"olive", "🫒"},
		{"om", "🕉️"},
		{"on", "🔛"},
		{"once", "🔂"},
		{"oncoming fist", "👊🏿"},
		{"oncoming", "🚘"},
		{"one", "🕜"},
		{"one-piece swimsuit", "🩱"},
		{"one-piece", "🩲"},
		{"one-thirty", "🕜"},
		{"onion", "🧅"},
		{"open for business", "🈺"},
		{"open hands", "👐🏿"},
		{"open mailbox with lowered flag", "📭"},
		{"open mailbox with raised flag", "📬"},
		{"open", "🔓"},
		{"opening", "🪟"},
		{"optical", "📀"},
		{"orange heart", "🧡"},
		{"orange", "🔸"},
		{"orangutan", "🦧"},
		{"organ", "🫁"},
		{"orienteering", "🧭"},
		{"orthodox cross", "☦️"},
		{"ostentatious", "🦚"},
		{"otter", "🦦"},
		{"outbox", "📤"},
		{"outgoing", "📩"},
		{"outlined", "🔳"},
		{"owl", "🦉"},
		{"ox", "♉"},
		{"oyster pail", "🥡"},
		{"oyster", "🦪"},
		{"o’clock", "🕚"},
		{"package", "📦"},
		{"packing", "🧳"},
		{"pad", "🗓️"},
		{"paddle", "🏓"},
		{"paella", "🥘"},
		{"page facing up", "📄"},
		{"page with curl", "📃"},
		{"page", "📄"},
		{"pager", "📟"},
		{"pail", "🪣"},
		{"paintbrush", "🖌️"},
		{"painting", "🖌️"},
		{"palette", "🎨"},
		{"palm", "🥥"},
		{"palms up together", "🤲🏿"},
		{"pan", "🥘"},
		{"pancake", "🥞"},
		{"pancakes", "🥞"},
		{"panda", "🐼"},
		{"pants", "🩳"},
		{"paper towels", "🧻"},
		{"paper", "🗞️"},
		{"paperclip", "🖇️"},
		{"parachute", "🪂"},
		{"parasail", "🪂"},
		{"parasite", "🪱"},
		{"parcel", "📦"},
		{"park", "🏞️"},
		{"parking", "🅿️"},
		{"parlor", "💇🏿"},
		{"parrot", "🦜"},
		{"part alternation mark", "〽️"},
		{"part", "〽️"},
		{"party", "🪅"},
		{"partying face", "🥳"},
		{"partying", "👯‍♀️"},
		{"passenger", "🚢"},
		{"passing grade", "🈴"},
		{"passport", "🛂"},
		{"password", "🔑"},
		{"pasta", "🍝"},
		{"pastry", "🥧"},
		{"patrol", "🚓"},
		{"pause button", "⏸️"},
		{"pause", "⏸️"},
		{"paw prints", "🐾"},
		{"paw", "🐾"},
		{"pc", "💻"},
		{"peace symbol", "☮️"},
		{"peace", "☮️"},
		{"peach", "🍑"},
		{"peacock", "🦚"},
		{"peahen", "🦚"},
		{"peanut", "🥜"},
		{"peanuts", "🥜"},
		{"pear", "🍐"},
		{"pearl", "🧋"},
		{"pedestrian", "🚷"},
		{"pen", "🔏"},
		{"pencil", "📝"},
		{"penguin", "🐧"},
		{"pensive", "😔"},
		{"people holding hands", "🧑🏿‍🤝‍🧑🏿"},
		{"people hugging", "🫂"},
		{"people with bunny ears", "👯"},
		{"people wrestling", "🤼"},
		{"pepper", "🫑"},
		{"performing arts", "🎭"},
		{"performing", "🎭"},
		{"persevere", "😣"},
		{"persevering face", "😣"},
		{"person biking", "🚴🏿"},
		{"person bouncing ball", "⛹🏿"},
		{"person bowing", "🙇🏿"},
		{"person cartwheeling", "🤸🏿"},
		{"person climbing", "🧗🏿"},
		{"person facepalming", "🤦🏿"},
		{"person fencing", "🤺"},
		{"person frowning", "🙍🏿"},
		{"person gesturing NO", "🙅🏿"},
		{"person gesturing OK", "🙆🏿"},
		{"person getting haircut", "💇🏿"},
		{"person getting massage", "💆🏿"},
		{"person golfing", "🏌🏿"},
		{"person in bed", "🛌🏿"},
		{"person in lotus position", "🧘🏿"},
		{"person in manual wheelchair", "🧑🏿‍🦽"},
		{"person in motorized wheelchair", "🧑🏿‍🦼"},
		{"person in steamy room", "🧖🏿"},
		{"person in suit levitating", "🕴🏿"},
		{"person in tuxedo", "🤵🏿"},
		{"person juggling", "🤹🏿"},
		{"person kneeling", "🧎🏿"},
		{"person lifting weights", "🏋🏿"},
		{"person mountain biking", "🚵🏿"},
		{"person playing handball", "🤾🏿"},
		{"person playing water polo", "🤽🏿"},
		{"person pouting", "🙎🏿"},
		{"person raising hand", "🙋🏿"},
		{"person rowing boat", "🚣🏿"},
		{"person running", "🏃🏿"},
		{"person shrugging", "🤷🏿"},
		{"person standing", "🧍🏿"},
		{"person surfing", "🏄🏿"},
		{"person swimming", "🏊🏿"},
		{"person taking bath", "🛀🏿"},
		{"person tipping hand", "💁🏿"},
		{"person walking", "🚶🏿"},
		{"person wearing turban", "👳🏿"},
		{"person with skullcap", "👲🏿"},
		{"person with veil", "👰🏿"},
		{"person with white cane", "🧑🏿‍🦯"},
		{"person", "🧑🏿‍❤️‍🧑🏾"},
		{"person: beard", "🧔🏿"},
		{"person: blond hair", "👱🏿"},
		{"personal", "💻"},
		{"pest", "🪰"},
		{"pester", "🦡"},
		{"pet", "🐇"},
		{"petri dish", "🧫"},
		{"phone", "📴"},
		{"physicist", "👩🏿‍🔬"},
		{"piano", "🎹"},
		{"pick", "⚒️"},
		{"pick-up", "🛻"},
		{"picket", "🪧"},
		{"pickle", "🥒"},
		{"pickup", "🛻"},
		{"picnic", "🧺"},
		{"picture", "🖼️"},
		{"pie", "🥧"},
		{"piece", "🧩"},
		{"pierogi", "🥟"},
		{"pig", "🐽"},
		{"pile of poo", "💩"},
		{"pill", "💊"},
		{"pilot", "👩🏿‍✈️"},
		{"pin", "📍"},
		{"pinched", "🤌🏿"},
		{"pinching hand", "🤏🏿"},
		{"pine decoration", "🎍"},
		{"pine", "🎍"},
		{"pineapple", "🍍"},
		{"ping pong", "🏓"},
		{"pink", "🏳️‍⚧️"},
		{"pinocchio", "🤥"},
		{"pirate flag", "🏴‍☠️"},
		{"pirate", "🏴‍☠️"},
		{"pistol", "🔫"},
		{"pita", "🫓"},
		{"pizza", "🍕"},
		{"piña colada", "🥥"},
		{"piñata", "🪅"},
		{"placard", "🪧"},
		{"place of worship", "🛐"},
		{"plane", "👩🏿‍✈️"},
		{"plant", "🌰"},
		{"plate", "🍽️"},
		{"play button", "▶️"},
		{"play or pause button", "⏯️"},
		{"play", "⏯️"},
		{"playful", "🦦"},
		{"playing", "🎴"},
		{"plaything", "🧸"},
		{"pleading face", "🥺"},
		{"please", "🙏🏿"},
		{"plug", "🔌"},
		{"plumage", "🪶"},
		{"plumber", "🪠"},
		{"plunder", "🏴‍☠️"},
		{"plunger", "🪠"},
		{"plus", "➕"},
		{"plush", "🧸"},
		{"point", "☝🏿"},
		{"polar bear", "🐻‍❄️"},
		{"pole", "🎣"},
		{"police", "🚨"},
		{"polish", "💅🏿"},
		{"polo", "🤽🏿"},
		{"poo", "💩"},
		{"poodle", "🐩"},
		{"pool 8 ball", "🎱"},
		{"poop", "💩"},
		{"popcorn", "🍿"},
		{"popper", "🎉"},
		{"popping", "🍾"},
		{"porkchop", "🥩"},
		{"porous", "🧽"},
		{"post office", "🏤"},
		{"post", "🚩"},
		{"postal", "📯"},
		{"postbox", "📮"},
		{"pot of food", "🍲"},
		{"pot", "🫖"},
		{"potable", "🚰"},
		{"potato", "🍠"},
		{"potsticker", "🥟"},
		{"potted plant", "🪴"},
		{"pouch", "👝"},
		{"poultry", "🍗"},
		{"pound", "💷"},
		{"pouting", "🙎🏿‍♀️"},
		{"prawn", "🍤"},
		{"pray", "🙏🏿"},
		{"prayer", "📿"},
		{"pregnant", "🤰🏿"},
		{"present", "🎁"},
		{"pretty", "🦋"},
		{"pretzel", "🥨"},
		{"previous scene", "⏮️"},
		{"previous track", "⏮️"},
		{"pride", "🏳️‍🌈"},
		{"prince", "🤴🏿"},
		{"princess", "👸🏿"},
		{"print", "🐾"},
		{"printer", "🖨️"},
		{"privacy", "🔏"},
		{"prize", "🏆"},
		{"professor", "👩🏿‍🏫"},
		{"prohibited", "🈲"},
		{"prohibited", "🔞"},
		{"projector", "📽️"},
		{"proof", "🧾"},
		{"prophecy", "🥠"},
		{"prosthetic", "🦿"},
		{"protest", "🪧"},
		{"proud", "🦚"},
		{"public address", "📢"},
		{"puck", "🏒"},
		{"pudding", "🍮"},
		{"puke", "🤮"},
		{"pulsating", "💓"},
		{"pulse", "🫀"},
		{"pump", "⛽"},
		{"punch", "👊🏿"},
		{"punctuation", "〰️"},
		{"punk rock", "🧷"},
		{"puppy eyes", "🥺"},
		{"purple heart", "💜"},
		{"purple", "🟪"},
		{"purse", "👜"},
		{"pushpin", "📍"},
		{"puzzle", "🧩"},
		{"quarter", "🌜"},
		{"queen", "👑"},
		{"quench", "🧯"},
		{"question", "❔"},
		{"quiet", "🔕"},
		{"r", "®️"},
		{"rabbit", "🐇"},
		{"raccoon", "🦝"},
		{"racehorse", "🐎"},
		{"racing", "🏁"},
		{"racquet", "🏸"},
		{"radio", "🔘"},
		{"radioactive", "☢️"},
		{"rage", "😡"},
		{"railway track", "🛤️"},
		{"railway", "🚟"},
		{"rain", "⛱️"},
		{"rainbow flag", "🏳️‍🌈"},
		{"rainbow", "🏳️‍🌈"},
		{"raised back of hand", "🤚🏿"},
		{"raised fist", "✊🏿"},
		{"raised hand", "✋🏿"},
		{"raised", "🙋🏿"},
		{"raising hand", "🙋🏿‍♀️"},
		{"raising hands", "🙌🏿"},
		{"ram", "♈"},
		{"ramen", "🍜"},
		{"rancher", "👩🏿‍🌾"},
		{"rat", "🐀"},
		{"rays", "☀️"},
		{"razor", "🪒"},
		{"rebound", "🪃"},
		{"receipt", "🧾"},
		{"receive", "📥"},
		{"receiver", "📞"},
		{"record button", "⏺️"},
		{"record", "⏺️"},
		{"recovering", "❤️‍🩹"},
		{"recreational", "🚙"},
		{"recuperating", "❤️‍🩹"},
		{"recycle", "♻️"},
		{"recycling symbol", "♻️"},
		{"red envelope", "🧧"},
		{"red exclamation mark", "❗"},
		{"red hair", "👩🏿‍🦰"},
		{"red heart", "❤️"},
		{"red paper lantern", "🏮"},
		{"red question mark", "❓"},
		{"red triangle pointed down", "🔻"},
		{"red triangle pointed up", "🔺"},
		{"red", "🔻"},
		{"red-faced", "🥵"},
		{"redhead", "🦰"},
		{"reflection", "🪞"},
		{"reflector", "🪞"},
		{"registered", "®️"},
		{"relaxed", "☺️"},
		{"relief", "😮‍💨"},
		{"relieved", "😥"},
		{"religion", "🕎"},
		{"reload", "🔃"},
		{"reminder", "🎗️"},
		{"repeat button", "🔁"},
		{"repeat single button", "🔂"},
		{"repeat", "🔁"},
		{"repercussion", "🪃"},
		{"reptile", "🦎"},
		{"rescue worker’s helmet", "⛑️"},
		{"reserved", "🈯"},
		{"resort", "⛵"},
		{"respiration", "🫁"},
		{"restroom", "🚾"},
		{"reverse button", "◀️"},
		{"reverse", "◀️"},
		{"revolver", "🔫"},
		{"revolving hearts", "💞"},
		{"revolving", "🚨"},
		{"rewind", "⏪"},
		{"rhinoceros", "🦏"},
		{"rhythm", "🪘"},
		{"ribbon", "🎗️"},
		{"rice", "🍛"},
		{"right anger bubble", "🗯️"},
		{"right arrow curving down", "⤵️"},
		{"right arrow curving left", "↩️"},
		{"right arrow curving up", "⤴️"},
		{"right arrow", "➡️"},
		{"right", "⏯️"},
		{"right-facing fist", "🤜🏿"},
		{"rightwards", "🤜🏿"},
		{"ring", "💍"},
		{"ringed planet", "🪐"},
		{"ringlets", "🦱"},
		{"roach", "🪳"},
		{"road", "🛣️"},
		{"roasted", "🍠"},
		{"robot", "🤖"},
		{"rock", "🥌"},
		{"rock-on", "🤘🏿"},
		{"rocket", "🚀"},
		{"rofl", "🤣"},
		{"roll of paper", "🧻"},
		{"roll", "🥐"},
		{"rolled", "🗞️"},
		{"rolled-up newspaper", "🗞️"},
		{"roller", "🛼"},
		{"rolling on the floor laughing", "🤣"},
		{"rolling", "🙄"},
		{"rolodex", "📇"},
		{"romance", "💒"},
		{"rooster", "🐓"},
		{"rope", "🪢"},
		{"rose", "🌹"},
		{"rosette", "🏵️"},
		{"rotfl", "🤣"},
		{"rotting", "🪰"},
		{"round pushpin", "📍"},
		{"roundhouse", "🛖"},
		{"rowboat", "🚣🏿‍♀️"},
		{"rucksack", "🎒"},
		{"rugby", "🏉"},
		{"ruler", "📐"},
		{"rung", "🪜"},
		{"running shoe", "👟"},
		{"running", "🎽"},
		{"rushed", "😰"},
		{"russia", "🪆"},
		{"sacred heart", "❤️‍🔥"},
		{"sad but relieved face", "😥"},
		{"sad", "😿"},
		{"safety pin", "🧷"},
		{"safety", "🦺"},
		{"sailboat", "⛵"},
		{"sake", "🍶"},
		{"salad", "🥗"},
		{"salon", "💆🏿"},
		{"salt", "🧂"},
		{"sand", "⏳"},
		{"sandal", "👡"},
		{"sandals", "🩴"},
		{"sandwich", "🥪"},
		{"santa", "🎅🏿"},
		{"sarcastic", "🤌🏿"},
		{"sari", "🥻"},
		{"sash", "🎽"},
		{"sassy", "💁🏿‍♀️"},
		{"satchel", "🎒"},
		{"satellite", "📡"},
		{"satisfied", "😆"},
		{"saturn", "🪐"},
		{"saturnine", "🪐"},
		{"sauna", "🧖🏿‍♀️"},
		{"sauropod", "🦕"},
		{"sausage", "🌭"},
		{"savouring", "😋"},
		{"saw", "🪚"},
		{"sax", "🎷"},
		{"saxophone", "🎷"},
		{"scale", "⚖️"},
		{"scales", "♎"},
		{"scared", "😱"},
		{"scarf", "🧣"},
		{"schmear", "🥯"},
		{"school", "🎒"},
		{"science", "🔭"},
		{"scientist", "🥼"},
		{"scissors", "✂️"},
		{"scooter", "🛴"},
		{"score", "🎼"},
		{"scorpio", "🦂"},
		{"scorpion", "♏"},
		{"scorpius", "♏"},
		{"scream", "😱"},
		{"screw", "🪛"},
		{"screwdriver", "🪛"},
		{"scroll", "📜"},
		{"scuba", "🤿"},
		{"sea Lion", "🦭"},
		{"sea", "⛵"},
		{"seafood", "🦞"},
		{"seal", "🦭"},
		{"search", "🔎"},
		{"seat", "🪑"},
		{"second", "🥈"},
		{"secret", "㊙️"},
		{"secure", "🔐"},
		{"see", "🙈"},
		{"see-no-evil monkey", "🙈"},
		{"seedling", "🌱"},
		{"selfie", "🤳🏿"},
		{"selling point", "🪝"},
		{"semi", "🚛"},
		{"sent", "📤"},
		{"serpent", "⛎"},
		{"service charge", "🈂️"},
		{"service", "🐕‍🦺"},
		{"set", "📐"},
		{"seven", "🕢"},
		{"seven-thirty", "🕢"},
		{"sewing", "🪡"},
		{"shake", "🤝🏿"},
		{"shaker", "🧂"},
		{"shallow pan of food", "🥘"},
		{"shallow", "🥘"},
		{"shampoo", "🧴"},
		{"shamrock", "☘️"},
		{"shark", "🦈"},
		{"sharp", "🪒"},
		{"shave", "🪒"},
		{"shaved", "🍧"},
		{"shaven", "🦲"},
		{"sheaf of rice", "🌾"},
		{"shedding", "🌳"},
		{"sheep", "🐑"},
		{"shell", "🐚"},
		{"shellfish", "🦐"},
		{"shield", "🛡️"},
		{"shining", "🌟"},
		{"shinkansen", "🚅"},
		{"shinto", "⛩️"},
		{"ship", "🔱"},
		{"shirt", "👕"},
		{"shocked", "😲"},
		{"shoe", "👢"},
		{"shooting", "🌠"},
		{"shopping bags", "🛍️"},
		{"shopping", "🛒"},
		{"shortcake", "🍰"},
		{"shorts", "🩳"},
		{"shot", "💉"},
		{"shower", "🚿"},
		{"shrimp", "🦐"},
		{"shrine", "⛩️"},
		{"shrug", "🤷🏿‍♀️"},
		{"shuffle tracks button", "🔀"},
		{"shush", "🤫"},
		{"shushing face", "🤫"},
		{"shuttlecock", "🏸"},
		{"sick", "💊"},
		{"sign of the horns", "🤘🏿"},
		{"sign", "➗"},
		{"signal", "🚦"},
		{"silent", "🔕"},
		{"silhouette", "👥"},
		{"silver", "🪙"},
		{"singer", "👩🏿‍🎤"},
		{"sit", "🪑"},
		{"six", "🕡"},
		{"six-thirty", "🕡"},
		{"skate", "⛸️"},
		{"skateboard", "🛹"},
		{"skeleton", "🦴"},
		{"skeptic", "🤨"},
		{"skewer", "🍡"},
		{"ski", "🎿"},
		{"skier", "⛷️"},
		{"skill", "🤹🏿"},
		{"skin tone", "🏿"},
		{"skis", "🎿"},
		{"skull and crossbones", "☠️"},
		{"skull", "☠️"},
		{"skullcap", "👲🏿"},
		{"skunk", "🦨"},
		{"skydive", "🪂"},
		{"sled", "🛷"},
		{"sledge", "🛷"},
		{"sleep", "🛏️"},
		{"sleeping face", "😴"},
		{"sleepy face", "😪"},
		{"sleigh", "🛷"},
		{"sleuth", "🕵🏿‍♀️"},
		{"slice", "🍰"},
		{"slider", "🎚️"},
		{"slightly frowning face", "🙁"},
		{"slightly smiling face", "🙂"},
		{"slip-on", "🥿"},
		{"slipper", "🥿"},
		{"slot machine", "🎰"},
		{"slot", "🎰"},
		{"sloth", "🦥"},
		{"slow", "🦥"},
		{"sly", "🦝"},
		{"small airplane", "🛩️"},
		{"small amount", "🤏🏿"},
		{"small blue diamond", "🔹"},
		{"small orange diamond", "🔸"},
		{"small", "🦐"},
		{"smile", "😼"},
		{"smiling cat with heart-eyes", "😻"},
		{"smiling face with halo", "😇"},
		{"smiling face with heart-eyes", "😍"},
		{"smiling face with hearts", "🥰"},
		{"smiling face with horns", "😈"},
		{"smiling face with smiling eyes", "😊"},
		{"smiling face with sunglasses", "😎"},
		{"smiling face with tear", "🥲"},
		{"smiling face", "☺️"},
		{"smiling", "🥲"},
		{"smirk", "😏"},
		{"smirking face", "😏"},
		{"smoking", "🚭"},
		{"snail", "🐌"},
		{"snake", "⛎"},
		{"snare", "🪤"},
		{"sneaker", "👟"},
		{"sneeze", "🤧"},
		{"sneezing face", "🤧"},
		{"snorkeling", "🤿"},
		{"snow", "🎿"},
		{"snow-capped mountain", "🏔️"},
		{"snowboard", "🏂🏿"},
		{"snowboarder", "🏂🏿"},
		{"snowflake", "❄️"},
		{"snowman without snow", "⛄"},
		{"snowman", "⛄"},
		{"soap", "🧼"},
		{"soapdish", "🧼"},
		{"soar", "🪁"},
		{"sob", "😭"},
		{"soccer", "⚽"},
		{"socks", "🧦"},
		{"soda", "🥤"},
		{"soft", "🔈"},
		{"softball", "🥎"},
		{"software", "👩🏿‍💻"},
		{"soldier", "🪖"},
		{"solid", "🪨"},
		{"soon", "🔜"},
		{"sorcerer", "🧙🏿‍♂️"},
		{"sorceress", "🧙🏿‍♀️"},
		{"sorry", "🙇🏿‍♀️"},
		{"sos", "🆘"},
		{"south", "⬇️"},
		{"southeast", "↘️"},
		{"southwest", "↙️"},
		{"sow", "🐖"},
		{"space", "☄️"},
		{"spade suit", "♠️"},
		{"spaghetti", "🍝"},
		{"spanner", "🔧"},
		{"sparkle", "❇️"},
		{"sparkler", "🎇"},
		{"sparkles", "✨"},
		{"sparkling heart", "💖"},
		{"speak", "🗣️"},
		{"speak-no-evil monkey", "🙊"},
		{"speaker high volume", "🔊"},
		{"speaker low volume", "🔈"},
		{"speaker medium volume", "🔉"},
		{"speaker", "🔇"},
		{"speaking", "🗣️"},
		{"speculum", "🪞"},
		{"speech bubble", "👁️‍🗨️"},
		{"speech", "🗨️"},
		{"speed", "🚅"},
		{"speedboat", "🚤"},
		{"spider", "🕸️"},
		{"spiny", "🦔"},
		{"spiral notepad", "🗒️"},
		{"spiral", "🗓️"},
		{"splashing", "💦"},
		{"splayed", "🖐🏿"},
		{"split", "🪓"},
		{"spock", "🖖🏿"},
		{"sponge", "🧽"},
		{"spool", "🧵"},
		{"spoon", "🥄"},
		{"sport utility vehicle", "🚙"},
		{"sport utility", "🚙"},
		{"sports medal", "🏅"},
		{"spots", "🦒"},
		{"spouting", "🐳"},
		{"springs", "♨️"},
		{"spy", "🕵🏿‍♀️"},
		{"square", "🔲"},
		{"squeeze box", "🪗"},
		{"squid", "🦑"},
		{"squinting face with tongue", "😝"},
		{"squirrel", "🐿️"},
		{"stadium", "🏟️"},
		{"staff", "⚕️"},
		{"stand", "🧍🏿"},
		{"standing", "🧍🏿‍♀️"},
		{"star and crescent", "☪️"},
		{"star of David", "✡️"},
		{"star", "✴️"},
		{"star-struck", "🤩"},
		{"station", "⛽"},
		{"statue", "🗿"},
		{"steak", "🥩"},
		{"stealth", "🥷🏿"},
		{"steam room", "🧖🏿‍♀️"},
		{"steam", "🚂"},
		{"steaming", "♨️"},
		{"step", "🪜"},
		{"stethoscope", "🩺"},
		{"stew", "🍲"},
		{"stick", "🥍"},
		{"stink", "🦨"},
		{"stitches", "🪡"},
		{"stocking", "🧦"},
		{"stomp", "🦶🏿"},
		{"stone", "🪨"},
		{"stop button", "⏹️"},
		{"stop", "⏹️"},
		{"stopwatch", "⏱️"},
		{"store", "🏬"},
		{"straight edge", "📏"},
		{"straight ruler", "📏"},
		{"straw", "🧃"},
		{"strawberry", "🍓"},
		{"streamer", "🎏"},
		{"string", "🧵"},
		{"stringed", "🪕"},
		{"stripe", "🦓"},
		{"student", "👩🏿‍🎓"},
		{"studio", "🎙️"},
		{"stuffed", "🧸"},
		{"stuffy", "🧐"},
		{"stunned", "😯"},
		{"subway", "🚇"},
		{"suction", "🪠"},
		{"suit", "🕴🏿"},
		{"sun behind cloud", "⛅"},
		{"sun behind large cloud", "🌥️"},
		{"sun behind rain cloud", "🌦️"},
		{"sun behind small cloud", "🌤️"},
		{"sun with face", "🌞"},
		{"sun", "⛱️"},
		{"sunflower", "🌻"},
		{"sunglasses", "🕶️"},
		{"sunny", "☀️"},
		{"sunrise over mountains", "🌄"},
		{"sunrise", "🌅"},
		{"sunscreen", "🧴"},
		{"sunset", "🌇"},
		{"superhero", "🦸🏿"},
		{"superpower", "🦹🏿‍♀️"},
		{"supervillain", "🦹🏿"},
		{"surfing", "🏄🏿‍♀️"},
		{"surprised", "🙀"},
		{"sushi", "🍣"},
		{"suspension", "🚟"},
		{"sutures", "🪡"},
		{"swan", "🦢"},
		{"swearing", "🤬"},
		{"sweat droplets", "💦"},
		{"sweat", "💧"},
		{"sweating", "🥵"},
		{"sweeping", "🧹"},
		{"sweet", "🧃"},
		{"swim", "👙"},
		{"swimming", "🥽"},
		{"swimsuit", "🩲"},
		{"swirl", "🍥"},
		{"sword", "🤺"},
		{"swords", "⚔️"},
		{"sympathy", "😮"},
		{"synagogue", "🕍"},
		{"syringe", "💉"},
		{"t-shirt", "👕"},
		{"table tennis", "🏓"},
		{"tableware", "🥄"},
		{"tabs", "📑"},
		{"taco", "🌮"},
		{"tada", "🎉"},
		{"taekwondo", "🥋"},
		{"tailoring", "🪡"},
		{"takeout box", "🥡"},
		{"talisman", "🧿"},
		{"talk", "🦜"},
		{"tamale", "🫔"},
		{"tanabata tree", "🎋"},
		{"tangerine", "🍊"},
		{"tangled", "🪢"},
		{"tao", "☯️"},
		{"taoist", "☯️"},
		{"tape", "📼"},
		{"target", "🎯"},
		{"taste", "😝"},
		{"taxi", "🚖"},
		{"tea", "🧋"},
		{"teacher", "👩🏿‍🏫"},
		{"teacup without handle", "🍵"},
		{"teacup", "🍵"},
		{"teapot", "🫖"},
		{"tear", "😿"},
		{"tear-off calendar", "📆"},
		{"technologist", "👩🏿‍💻"},
		{"teddy bear", "🧸"},
		{"teeth", "🪥"},
		{"telephone", "📴"},
		{"telescope", "🔭"},
		{"television", "📺"},
		{"teller", "🏧"},
		{"temple", "🕍"},
		{"tempura", "🍤"},
		{"ten", "🕥"},
		{"ten-thirty", "🕥"},
		{"tennis", "🎾"},
		{"tent", "🎪"},
		{"terrapin", "🐢"},
		{"test tube", "🧪"},
		{"thanks", "🫂"},
		{"theater", "🎭"},
		{"theatre", "🎭"},
		{"therapist", "👩🏿‍⚕️"},
		{"thermometer", "🌡️"},
		{"thinking", "🤔"},
		{"third", "🥉"},
		{"thirty", "🕦"},
		{"thong sandal", "🩴"},
		{"thong sandals", "🩴"},
		{"thongs", "🩴"},
		{"thought", "💭"},
		{"thread", "🧵"},
		{"three", "🕞"},
		{"three-thirty", "🕞"},
		{"thumb", "👎🏿"},
		{"thumbs down", "👎🏿"},
		{"thumbs up", "👍🏿"},
		{"thunder", "⛈️"},
		{"tichel", "🧕🏿"},
		{"ticket", "🎫"},
		{"tie", "👔"},
		{"tiger", "🐅"},
		{"timber", "🪵"},
		{"timer", "⏲️"},
		{"tipping hand", "💁🏿‍♀️"},
		{"tipping", "💁🏿"},
		{"tipsy", "🥴"},
		{"tired", "🥱"},
		{"tm", "™️"},
		{"toadstool", "🍄"},
		{"toilet paper", "🧻"},
		{"toilet", "🪠"},
		{"tomato", "🍅"},
		{"tombstone", "🪦"},
		{"tongue", "👅"},
		{"tool", "🔱"},
		{"toolbox", "🧰"},
		{"tooth", "🦷"},
		{"toothbrush", "🪥"},
		{"top", "🔝"},
		{"tophat", "🎩"},
		{"torch", "🔦"},
		{"tornado", "🌪️"},
		{"tortoise", "🐢"},
		{"totally", "😲"},
		{"touched", "🥲"},
		{"tower", "🗼"},
		{"toy", "🧸"},
		{"trackball", "🖲️"},
		{"tractor", "🚜"},
		{"trade mark", "™️"},
		{"trademark", "™️"},
		{"tradesperson", "👩🏿‍🔧"},
		{"traffic", "⛔"},
		{"train", "🛤️"},
		{"tram", "🚎"},
		{"tramway", "🚡"},
		{"transgender symbol", "⚧️"},
		{"transgender", "🏳️‍⚧️"},
		{"transparent", "🪟"},
		{"trap", "🪤"},
		{"travel", "🧳"},
		{"tray", "📥"},
		{"treasure", "🏴‍☠️"},
		{"tree", "🎋"},
		{"trend", "📉"},
		{"triangle", "⏮️"},
		{"triangular flag", "🚩"},
		{"triangular ruler", "📐"},
		{"trident", "🔱"},
		{"triumph", "😤"},
		{"trolley", "🛒"},
		{"trolleybus", "🚎"},
		{"trophy", "🏆"},
		{"tropical", "🍹"},
		{"trouble", "😵‍💫"},
		{"trousers", "👖"},
		{"truck", "🚛"},
		{"trumpet", "🎺"},
		{"tshirt", "👕"},
		{"tuk tuk", "🛺"},
		{"tulip", "🌷"},
		{"tumbler", "🥃"},
		{"turban", "👳🏿‍♀️"},
		{"turkey", "🦃"},
		{"turtle", "🐢"},
		{"tusk", "🦣"},
		{"tuxedo", "🤵🏿‍♀️"},
		{"tv", "📺"},
		{"twelve", "🕧"},
		{"twelve-thirty", "🕧"},
		{"twine", "🪢"},
		{"twins", "♊"},
		{"twist", "🪢"},
		{"twisted", "🥨"},
		{"twister", "🌀"},
		{"two hearts", "💕"},
		{"two", "🕝"},
		{"two-hump camel", "🐫"},
		{"two-thirty", "🕝"},
		{"type 1–2", "🏻"},
		{"type 3", "🏼"},
		{"type 4", "🏽"},
		{"type 5", "🏾"},
		{"type 6", "🏿"},
		{"typhoon", "🌀"},
		{"ufo", "👾"},
		{"ugly duckling", "🦢"},
		{"ultimate", "🥏"},
		{"umbrella on ground", "⛱️"},
		{"umbrella with rain drops", "☔"},
		{"umbrella", "⛱️"},
		{"unamused", "😒"},
		{"unbounded", "♾️"},
		{"undead", "🧟‍♀️"},
		{"underage", "🔞"},
		{"underarm", "🥎"},
		{"underwear", "🩳"},
		{"uneven eyes", "🥴"},
		{"unexpressive", "😑"},
		{"unhappy", "😒"},
		{"unicorn", "🦄"},
		{"uniform", "🥋"},
		{"universal", "♾️"},
		{"unlock", "🔓"},
		{"unlocked", "🔓"},
		{"unlucky", "🐈‍⬛"},
		{"unspecified gender", "🧓🏿"},
		{"up arrow", "⬆️"},
		{"up", "🆙"},
		{"up-down arrow", "↕️"},
		{"up-left arrow", "↖️"},
		{"up-right arrow", "↗️"},
		{"uppercase", "🔠"},
		{"upside-down", "🙃"},
		{"upward", "📈"},
		{"upwards button", "🔼"},
		{"urn", "⚱️"},
		{"useless", "🪴"},
		{"v", "✌🏿"},
		{"vacancy", "🈳"},
		{"valentine", "💝"},
		{"vampire", "🦇"},
		{"vat", "🪣"},
		{"vegetable", "🥜"},
		{"vehicle", "🚁"},
		{"veil", "👰🏿‍♀️"},
		{"versus", "🆚"},
		{"vertical traffic light", "🚦"},
		{"vertical", "⏸️"},
		{"vest", "🦺"},
		{"vhs", "📼"},
		{"vibration", "📳"},
		{"vice", "🗜️"},
		{"victory", "✌🏿"},
		{"vicuña", "🦙"},
		{"video game", "🕹️"},
		{"video", "📼"},
		{"videocassette", "📼"},
		{"view", "🪟"},
		{"villain", "🦹🏿‍♀️"},
		{"violin", "🎻"},
		{"virus", "🦠"},
		{"volcano", "🌋"},
		{"volleyball", "🏐"},
		{"voltage", "⚡"},
		{"vomit", "🤮"},
		{"vs", "🆚"},
		{"vulcan salute", "🖖🏿"},
		{"vulcan", "🖖🏿"},
		{"waffle", "🧇"},
		{"walk", "🚶🏿‍♀️"},
		{"walking dead", "🧟‍♀️"},
		{"walking", "🚶🏿"},
		{"wall", "🧱"},
		{"waning", "🌘"},
		{"warning", "⚠️"},
		{"warrior", "🪖"},
		{"wastebasket", "🗑️"},
		{"watch", "⌚"},
		{"water polo", "🤽🏿‍♀️"},
		{"water", "♒"},
		{"watermelon", "🍉"},
		{"wave", "🌊"},
		{"waving", "🏳️"},
		{"wavy mouth", "🥴"},
		{"wavy", "〰️"},
		{"waxing", "🌔"},
		{"wc", "🚾"},
		{"weapon", "🛡️"},
		{"weary", "🙀"},
		{"weather", "☁️"},
		{"web", "🕸️"},
		{"wedding", "💒"},
		{"weight lifter", "🏋🏿‍♀️"},
		{"weight", "🏋🏿"},
		{"welding", "🥽"},
		{"well", "❤️‍🩹"},
		{"west", "⬅️"},
		{"whale", "🐋"},
		{"wheel of dharma", "☸️"},
		{"wheel", "☸️"},
		{"wheelchair symbol", "♿"},
		{"wheelchair", "👩🏿‍🦽"},
		{"whew", "😥"},
		{"whirlwind", "🌪️"},
		{"whisky", "🥃"},
		{"whisper", "😮‍💨"},
		{"whistle", "😮‍💨"},
		{"white cane", "🦯"},
		{"white circle", "⚪"},
		{"white exclamation mark", "❕"},
		{"white flag", "🏳️"},
		{"white flower", "💮"},
		{"white hair", "👩🏿‍🦳"},
		{"white large square", "⬜"},
		{"white medium square", "◻️"},
		{"white medium-small square", "◽"},
		{"white question mark", "❔"},
		{"white small square", "▫️"},
		{"white square button", "🔳"},
		{"white", "🏳️‍⚧️"},
		{"white-collar", "👩🏿‍💼"},
		{"whoa", "😵‍💫"},
		{"whoops", "🤭"},
		{"wicked", "🖤"},
		{"wild cabbage", "🥦"},
		{"wildcard", "🃏"},
		{"wilted", "🥀"},
		{"wind", "🎐"},
		{"window", "🪟"},
		{"wine", "🍷"},
		{"wings", "💸"},
		{"wink", "😜"},
		{"winking face with tongue", "😜"},
		{"winking face", "😉"},
		{"wise", "🦉"},
		{"wisent", "🦬"},
		{"witch", "🧹"},
		{"withershins", "🔄"},
		{"witness", "👁️‍🗨️"},
		{"wizard", "🪄"},
		{"wolf", "🐺"},
		{"woman and man holding hands", "👫🏿"},
		{"woman bouncing ball", "⛹🏿‍♀️"},
		{"woman cartwheeling", "🤸🏿‍♀️"},
		{"woman climbing", "🧗🏿‍♀️"},
		{"woman elf", "🧝🏿‍♀️"},
		{"woman facepalming", "🤦🏿‍♀️"},
		{"woman fairy", "🧚🏿‍♀️"},
		{"woman genie", "🧞‍♀️"},
		{"woman gesturing NO", "🙅🏿‍♀️"},
		{"woman gesturing OK", "🙆🏿‍♀️"},
		{"woman getting haircut", "💇🏿‍♀️"},
		{"woman getting massage", "💆🏿‍♀️"},
		{"woman golfing", "🏌🏿‍♀️"},
		{"woman health worker", "👩🏿‍⚕️"},
		{"woman in lotus position", "🧘🏿‍♀️"},
		{"woman in manual wheelchair", "👩🏿‍🦽"},
		{"woman in motorized wheelchair", "👩🏿‍🦼"},
		{"woman in steamy room", "🧖🏿‍♀️"},
		{"woman in tuxedo", "🤵🏿‍♀️"},
		{"woman lifting weights", "🏋🏿‍♀️"},
		{"woman mage", "🧙🏿‍♀️"},
		{"woman office worker", "👩🏿‍💼"},
		{"woman playing handball", "🤾🏿‍♀️"},
		{"woman playing water polo", "🤽🏿‍♀️"},
		{"woman raising hand", "🙋🏿‍♀️"},
		{"woman rowing boat", "🚣🏿‍♀️"},
		{"woman shrugging", "🤷🏿‍♀️"},
		{"woman superhero", "🦸🏿‍♀️"},
		{"woman supervillain", "🦹🏿‍♀️"},
		{"woman swimming", "🏊🏿‍♀️"},
		{"woman tipping hand", "💁🏿‍♀️"},
		{"woman vampire", "🧛🏿‍♀️"},
		{"woman walking", "🚶🏿‍♀️"},
		{"woman wearing turban", "👳🏿‍♀️"},
		{"woman with headscarf", "🧕🏿"},
		{"woman with veil", "👰🏿‍♀️"},
		{"woman with white cane", "👩🏿‍🦯"},
		{"woman zombie", "🧟‍♀️"},
		{"woman", "♀️"},
		{"woman: beard", "🧔🏿‍♀️"},
		{"woman: blond hair", "👱🏿‍♀️"},
		{"woman’s boot", "👢"},
		{"woman’s clothes", "👚"},
		{"woman’s hat", "👒"},
		{"woman’s sandal", "👡"},
		{"women holding hands", "👭🏿"},
		{"women with bunny ears", "👯‍♀️"},
		{"women wrestling", "🤼‍♀️"},
		{"women", "👭🏿"},
		{"women’s room", "🚺"},
		{"won", "😤"},
		{"wood", "🪓"},
		{"wool", "🦙"},
		{"woolly", "🦣"},
		{"woozy face", "🥴"},
		{"worker", "👷🏿‍♀️"},
		{"world", "🗺️"},
		{"worm", "🪱"},
		{"worried", "😟"},
		{"worship", "🛐"},
		{"wrap", "🌯"},
		{"wrapped", "🎁"},
		{"wrench", "🔧"},
		{"wrestle", "🤼‍♀️"},
		{"wrestler", "🤼"},
		{"write", "✍🏿"},
		{"writing hand", "✍🏿"},
		{"wry", "😼"},
		{"x", "❎"},
		{"yacht", "⛵"},
		{"yang", "☯️"},
		{"yarn", "🧶"},
		{"yawn", "🥱"},
		{"yawning face", "🥱"},
		{"yellow heart", "💛"},
		{"yellow", "🟨"},
		{"yen", "💹"},
		{"yin", "☯️"},
		{"yo-yo", "🪀"},
		{"yoga", "🧘🏿‍♀️"},
		{"young", "🌱"},
		{"yum", "😋"},
		{"yurt", "🛖"},
		{"yuèbǐng", "🥮"},
		{"zany face", "🤪"},
		{"zap", "⚡"},
		{"zebra", "🦓"},
		{"zipper", "🤐"},
		{"zipper-mouth face", "🤐"},
		{"zodiac", "⛎"},
		{"zombie", "🧟"},
		{"zzz", "💤"},
		{"zōri", "🩴"},
		{"×", "❎"},
		{"÷", "➗"},
		{"−", "➖"},
		{"✓", "✔️"},
		{"〒♪&%", "🔣"},
		{"ココ", "🈁"},
		{"サ", "🈂️"},
		{"割", "🈹"},
		{"可", "🉑"},
		{"合", "🈴"},
		{"営", "🈺"},
		{"得", "🉐"},
		{"指", "🈯"},
		{"月", "🈷️"},
		{"有", "🈶"},
		{"満", "🈵"},
		{"無", "🈚"},
		{"申", "🈸"},
		{"祝", "㊗️"},
		{"禁", "🈲"},
		{"秘", "㊙️"},
		{"空", "🈳"}
	};

	return emoji;
}


#endif
