.\" This man page for createstructure
.TH createstructure "1" "2021-04-15" "createstructure 08.01" "User Commands"
.SH NAME
createstructure
.SH SYNOPSIS
.B createstructure - runs the creator
.br
.B createstructure [-h | --help] - Help
.br
.B createstructure [-v | --verbose] - You will see more infos
.br
.B createstructure [-V | --version] - Show you the version
.br
.B createstructure [-l | --login] - Do the login (NEEDS ADMINISTRATOR RIGHTS)
.SH DESCRIPTION
With this programm you can easily create a repository on GitHub with a basic template, personalized for your use.
.SH AUTHORS
Castellani Davide: owner