#!/bin/bash
echo "Install supplementary parts"
pip3 install createstructure==7.2
echo "Installed createstructure"

echo "-----------------------------------------------------------"
echo "---createstructure-remember-to-do: createstructure -v -l---"
echo "-----------------------------------------------------------"
