#!/bin/bash
echo "-------------------------------------------------------------"
echo "---createstructure-remember-to-do: sudo createstructure -l---"
echo "-------------------------------------------------------------"
